mkdir app-class
echo "android.app.ActionBar\$Tab
android.app.ActionBar
android.app.Activity\$ManagedCursor
android.app.Activity\$ManagedDialog
android.app.Activity\$NonConfigurationInstances
android.app.Activity\$RequestFinishCallback\$\$ExternalSyntheticLambda0
android.app.ActivityClient
android.app.ActivityManager\$\$ExternalSyntheticLambda0
android.app.ActivityManager\$AppTask
android.app.ActivityManager\$RecentTaskInfo\$PersistedTaskSnapshotData
android.app.ActivityManager\$TaskDescription\$Builder
android.app.ActivityManager
android.app.ActivityManagerInternal\$AppBackgroundRestrictionListener
android.app.ActivityManagerInternal\$ServiceNotificationPolicy
android.app.ActivityManagerInternal
android.app.ActivityManagerNative
android.app.ActivityManagerProto
android.app.ActivityOptions\$1\$1
android.app.ActivityOptions\$2\$1
android.app.ActivityTaskManager
android.app.ActivityThread\$\$ExternalSyntheticLambda2
android.app.ActivityThread\$\$ExternalSyntheticLambda3
android.app.ActivityThread\$\$ExternalSyntheticLambda4
android.app.ActivityThread\$\$ExternalSyntheticLambda5
android.app.ActivityThread\$1\$\$ExternalSyntheticLambda0
android.app.ActivityThread\$3
android.app.ActivityThread\$ActivityClientRecord
android.app.ActivityThread\$AndroidOs
android.app.ActivityThread\$AppBindData
android.app.ActivityThread\$ApplicationThread\$\$ExternalSyntheticLambda2
android.app.ActivityThread\$ApplicationThread\$1
android.app.ActivityThread\$BindServiceData
android.app.ActivityThread\$ContextCleanupInfo
android.app.ActivityThread\$CreateBackupAgentData
android.app.ActivityThread\$CreateServiceData
android.app.ActivityThread\$DumpComponentInfo
android.app.ActivityThread\$DumpHeapData
android.app.ActivityThread\$DumpResourcesData
android.app.ActivityThread\$Profiler
android.app.ActivityThread\$ProviderClientRecord
android.app.ActivityThread\$ProviderKey
android.app.ActivityThread\$ProviderRefCount
android.app.ActivityThread\$RequestAssistContextExtras
android.app.ActivityThread\$ServiceArgsData
android.app.ActivityThread\$UpdateCompatibilityData
android.app.ActivityTransitionCoordinator\$\$ExternalSyntheticLambda0
android.app.ActivityTransitionCoordinator\$\$ExternalSyntheticLambda1
android.app.ActivityTransitionCoordinator\$SharedElementOriginalState
android.app.ActivityTransitionState\$\$ExternalSyntheticLambda0
android.app.ActivityTransitionState\$1\$\$ExternalSyntheticLambda0
android.app.ActivityTransitionState\$1
android.app.ActivityTransitionState
android.app.AlarmClockInfoProto
android.app.AlarmManager
android.app.AlarmManagerProto
android.app.AlertDialog\$Builder
android.app.AppCompatCallbacks
android.app.AppComponentFactory
android.app.AppGlobals
android.app.AppOpsManager\$\$ExternalSyntheticLambda1
android.app.AppOpsManager\$\$ExternalSyntheticLambda2
android.app.AppOpsManager\$\$ExternalSyntheticLambda3
android.app.AppOpsManager\$\$ExternalSyntheticLambda6
android.app.AppOpsManager\$3\$\$ExternalSyntheticLambda0
android.app.AppOpsManager\$HistoricalOp\$\$ExternalSyntheticLambda0
android.app.AppOpsManager\$HistoricalOp\$\$ExternalSyntheticLambda1
android.app.AppOpsManager\$HistoricalOp\$\$ExternalSyntheticLambda2
android.app.AppOpsManager\$HistoricalOpsRequest\$Builder
android.app.AppOpsManager\$HistoricalOpsRequest
android.app.AppOpsManager\$OnOpActiveChangedListener
android.app.AppOpsManager\$OnOpNotedCallback\$1\$\$ExternalSyntheticLambda0
android.app.AppOpsManager\$OnOpNotedCallback
android.app.AppOpsManager\$OnOpStartedListener
android.app.AppOpsManager\$PausedNotedAppOpsCollection
android.app.AppOpsManager\$RestrictionBypass
android.app.AppOpsManager
android.app.AppOpsManagerInternal\$CheckOpsDelegate
android.app.AppOpsManagerInternal
android.app.AppProtoEnums
android.app.Application\$ActivityLifecycleCallbacks
android.app.ApplicationErrorReport\$AnrInfo
android.app.ApplicationErrorReport\$BatteryInfo
android.app.ApplicationErrorReport\$CrashInfo
android.app.ApplicationErrorReport\$RunningServiceInfo
android.app.ApplicationExitInfoProto
android.app.ApplicationLoaders\$CachedClassLoader
android.app.ApplicationLoaders
android.app.ApplicationPackageManager\$\$ExternalSyntheticLambda0
android.app.ApplicationPackageManager\$\$ExternalSyntheticLambda1
android.app.ApplicationPackageManager\$\$ExternalSyntheticLambda2
android.app.ApplicationPackageManager\$DexModuleRegisterResult
android.app.ApplicationPackageManager\$GetPackagesForUidResult
android.app.ApplicationPackageManager\$HasSystemFeatureQuery
android.app.ApplicationPackageManager\$ResourceName
android.app.ApplicationThreadConstants
android.app.BackStackRecord\$Op
android.app.ClientTransactionHandler
android.app.ComponentOptions
android.app.ConfigurationController
android.app.ContextImpl\$1
android.app.DexLoadReporter
android.app.Dialog\$\$ExternalSyntheticLambda0
android.app.DirectAction\$Builder
android.app.DownloadManager\$Query
android.app.DownloadManager\$Request
android.app.DownloadManager
android.app.DreamManager
android.app.EnterTransitionCoordinator\$\$ExternalSyntheticLambda0
android.app.EnterTransitionCoordinator\$\$ExternalSyntheticLambda1
android.app.EnterTransitionCoordinator\$2
android.app.EnterTransitionCoordinator\$3\$\$ExternalSyntheticLambda0
android.app.EnterTransitionCoordinator\$3\$\$ExternalSyntheticLambda1
android.app.EnterTransitionCoordinator\$9
android.app.EventLogTags
android.app.ExitTransitionCoordinator\$\$ExternalSyntheticLambda0
android.app.ExitTransitionCoordinator\$\$ExternalSyntheticLambda1
android.app.ExitTransitionCoordinator\$\$ExternalSyntheticLambda2
android.app.ExitTransitionCoordinator\$1
android.app.ExitTransitionCoordinator\$ExitTransitionCallbacks
android.app.Fragment\$\$ExternalSyntheticLambda0
android.app.Fragment\$AnimationInfo
android.app.FragmentContainer
android.app.FragmentController
android.app.FragmentManager\$FragmentLifecycleCallbacks
android.app.FragmentManager
android.app.FragmentManagerImpl\$1
android.app.FragmentManagerNonConfig
android.app.FragmentTransaction
android.app.FragmentTransition\$\$ExternalSyntheticLambda0
android.app.FragmentTransition\$\$ExternalSyntheticLambda1
android.app.FragmentTransition\$\$ExternalSyntheticLambda2
android.app.FragmentTransition\$\$ExternalSyntheticLambda3
android.app.FragmentTransition\$FragmentContainerTransition
android.app.FragmentTransition
android.app.GameManager
android.app.HomeVisibilityListener\$1\$\$ExternalSyntheticLambda0
android.app.HomeVisibilityListener
android.app.InstantAppResolverService\$InstantAppResolutionCallback
android.app.Instrumentation\$1ContextMenuRunnable
android.app.Instrumentation\$1MenuRunnable
android.app.Instrumentation\$ActivityMonitor
android.app.Instrumentation\$ActivityResult
android.app.Instrumentation\$ActivityWaiter
android.app.Instrumentation\$EmptyRunnable
android.app.Instrumentation\$InstrumentationThread
android.app.Instrumentation\$SyncRunnable
android.app.Instrumentation
android.app.KeyguardManager\$1\$\$ExternalSyntheticLambda0
android.app.KeyguardManager\$1\$\$ExternalSyntheticLambda1
android.app.KeyguardManager\$2\$\$ExternalSyntheticLambda0
android.app.KeyguardManager\$2\$\$ExternalSyntheticLambda1
android.app.KeyguardManager\$2\$\$ExternalSyntheticLambda2
android.app.KeyguardManager\$4\$\$ExternalSyntheticLambda0
android.app.KeyguardManager\$5\$\$ExternalSyntheticLambda0
android.app.KeyguardManager\$KeyguardDismissCallback
android.app.KeyguardManager\$KeyguardLock
android.app.KeyguardManager
android.app.LauncherActivity\$IconResizer
android.app.LauncherActivity\$ListItem
android.app.ListActivity\$1
android.app.ListFragment\$1
android.app.LoadedApk\$ReceiverDispatcher\$Args\$\$ExternalSyntheticLambda0
android.app.LoadedApk\$ReceiverDispatcher
android.app.LoadedApk\$ServiceDispatcher\$ConnectionInfo
android.app.LoadedApk\$ServiceDispatcher\$RunConnection
android.app.LoadedApk\$ServiceDispatcher
android.app.LoadedApk\$WarningContextClassLoader
android.app.LoadedApk
android.app.LoaderManager
android.app.LocalActivityManager
android.app.LocaleConfig
android.app.LocaleManager
android.app.Notification\$Action\$Builder
android.app.Notification\$BubbleMetadata\$Builder
android.app.Notification\$Builder\$\$ExternalSyntheticLambda0
android.app.Notification\$Builder
android.app.Notification\$CarExtender\$Builder
android.app.Notification\$CarExtender\$UnreadConversation
android.app.Notification\$Colors
android.app.Notification\$MessagingStyle\$Message
android.app.Notification\$StandardTemplateParams
android.app.Notification\$Style
android.app.Notification\$TemplateBindResult\$MarginSet
android.app.Notification\$TemplateBindResult
android.app.NotificationChannelGroupProto
android.app.NotificationChannelProto
android.app.NotificationHistory\$\$ExternalSyntheticLambda0
android.app.NotificationHistory\$HistoricalNotification\$Builder
android.app.NotificationHistory\$HistoricalNotification
android.app.NotificationManager
android.app.NotificationProto
android.app.PackageDeleteObserver
android.app.PackageInstallObserver
android.app.PendingIntent\$\$ExternalSyntheticLambda0
android.app.PendingIntent\$\$ExternalSyntheticLambda1
android.app.PendingIntentProto
android.app.PendingIntentStats
android.app.Person\$Builder
android.app.PictureInPictureParams\$Builder
android.app.PolicyProto
android.app.ProfilerInfoProto
android.app.PropertyInvalidatedCache\$1
android.app.PropertyInvalidatedCache\$AutoCorker
android.app.PropertyInvalidatedCache\$NoPreloadHolder
android.app.PropertyInvalidatedCache\$QueryHandler
android.app.PropertyInvalidatedCache
android.app.QueuedWork
android.app.RemoteInput\$Builder
android.app.ResourcesManager\$\$ExternalSyntheticLambda0
android.app.ResourcesManager\$\$ExternalSyntheticLambda1
android.app.ResourcesManager\$ActivityResource
android.app.ResourcesManager\$ActivityResources
android.app.ResourcesManager\$ApkAssetsSupplier
android.app.ResourcesManager\$ApkKey
android.app.ResourcesManager
android.app.ServiceStartNotAllowedException
android.app.SharedElementCallback
android.app.SharedPreferencesImpl\$1
android.app.SharedPreferencesImpl\$2
android.app.SharedPreferencesImpl\$EditorImpl\$\$ExternalSyntheticLambda0
android.app.SharedPreferencesImpl\$EditorImpl\$1
android.app.SharedPreferencesImpl\$EditorImpl\$2
android.app.SharedPreferencesImpl\$MemoryCommitResult
android.app.StackTrace
android.app.StatusBarManager\$\$ExternalSyntheticLambda0
android.app.StatusBarManager\$DisableInfo
android.app.StatusBarManager\$NearbyMediaDevicesProviderWrapper\$\$ExternalSyntheticLambda0
android.app.StatusBarManager\$RequestResultCallback\$\$ExternalSyntheticLambda0
android.app.StatusBarManager
android.app.StatusBarManagerProto
android.app.SystemServiceRegistry\$16\$\$ExternalSyntheticLambda0
android.app.SystemServiceRegistry
android.app.TaskInfo
android.app.TaskStackBuilder
android.app.UiAutomation\$IAccessibilityServiceClientImpl\$1\$\$ExternalSyntheticLambda0
android.app.UiAutomation
android.app.UiAutomationConnection\$1
android.app.UiAutomationConnection\$Repeater
android.app.UiModeManager\$OnProjectionStateChangedListenerResourceManager
android.app.UiModeManager
android.app.UriGrantsManager
android.app.VoiceInteractor\$2\$\$ExternalSyntheticLambda0
android.app.VoiceInteractor\$Request
android.app.VoiceInteractor
android.app.Vr2dDisplayProperties\$Builder
android.app.VrManager\$CallbackEntry\$1\$\$ExternalSyntheticLambda0
android.app.VrManager\$CallbackEntry\$2\$\$ExternalSyntheticLambda0
android.app.VrManager\$CallbackEntry
android.app.VrManager
android.app.VrStateCallback
android.app.WallpaperColors\$\$ExternalSyntheticLambda0
android.app.WallpaperColors\$\$ExternalSyntheticLambda1
android.app.WallpaperManager\$ColorManagementProxy
android.app.WallpaperManager\$Globals\$\$ExternalSyntheticLambda0
android.app.WallpaperManager\$Globals\$\$ExternalSyntheticLambda1
android.app.WallpaperManager\$OnColorsChangedListener
android.app.WallpaperManager
android.app.WindowConfigurationProto
android.app.admin.DeviceAdminInfo\$PolicyInfo
android.app.admin.DevicePolicyCache
android.app.admin.DevicePolicyEventLogger
android.app.admin.DevicePolicyKeyguardService\$1\$\$ExternalSyntheticLambda0
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda0
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda12
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda2
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda3
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda4
android.app.admin.DevicePolicyManager\$1\$\$ExternalSyntheticLambda0
android.app.admin.DevicePolicyManager\$InstallSystemUpdateCallback
android.app.admin.DevicePolicyManager
android.app.admin.DevicePolicyManagerInternal
android.app.admin.DevicePolicyResources\$Drawables\$Source
android.app.admin.DevicePolicyResources\$Drawables\$Style
android.app.admin.DevicePolicyResources\$Drawables
android.app.admin.DevicePolicyResources\$Strings\$Core
android.app.admin.DevicePolicyResources\$Strings\$DefaultAppSettings
android.app.admin.DevicePolicyResources\$Strings\$PermissionSettings
android.app.admin.DevicePolicyResources\$Strings\$Settings
android.app.admin.DevicePolicyResources\$Strings\$SystemUi
android.app.admin.DevicePolicyResources\$Strings\$Telecomm
android.app.admin.DevicePolicyResources\$Strings
android.app.admin.DevicePolicyResources
android.app.admin.DevicePolicyResourcesManager
android.app.admin.DevicePolicySafetyChecker
android.app.admin.DeviceStateCache
android.app.admin.FactoryResetProtectionPolicy\$Builder
android.app.admin.FreezePeriod
android.app.admin.FullyManagedDeviceProvisioningParams\$Builder
android.app.admin.ManagedProfileProvisioningParams\$Builder
android.app.admin.PasswordMetrics\$ComplexityBucket
android.app.admin.PasswordPolicy
android.app.admin.PreferentialNetworkServiceConfig\$\$ExternalSyntheticLambda0
android.app.admin.PreferentialNetworkServiceConfig\$\$ExternalSyntheticLambda1
android.app.admin.PreferentialNetworkServiceConfig\$\$ExternalSyntheticLambda2
android.app.admin.PreferentialNetworkServiceConfig\$Builder
android.app.admin.ProvisioningIntentHelper
android.app.admin.SecurityLog
android.app.admin.SecurityLogTags
android.app.admin.SystemUpdatePolicy\$\$ExternalSyntheticLambda0
android.app.admin.SystemUpdatePolicy\$InstallationOption
android.app.ambientcontext.AmbientContextEvent\$Builder
android.app.ambientcontext.AmbientContextEventRequest\$Builder
android.app.ambientcontext.AmbientContextManager\$\$ExternalSyntheticLambda0
android.app.ambientcontext.AmbientContextManager\$\$ExternalSyntheticLambda2
android.app.ambientcontext.AmbientContextManager
android.app.assist.AssistStructure\$AutofillOverlay
android.app.assist.AssistStructure\$ParcelTransferReader
android.app.assist.AssistStructure\$ViewNode
android.app.assist.AssistStructure\$ViewNodeText
android.app.assist.AssistStructure\$ViewStackEntry
android.app.assist.AssistStructure\$WindowNode
android.app.backup.BackupAgent\$FailRunnable
android.app.backup.BackupAgent\$IncludeExcludeRules
android.app.backup.BackupAgent\$SharedPrefsSynchronizer
android.app.backup.BackupDataInput\$EntityHeader
android.app.backup.BackupDataInput
android.app.backup.BackupDataInputStream
android.app.backup.BackupDataOutput
android.app.backup.BackupHelperDispatcher\$Header
android.app.backup.BackupHelperDispatcher
android.app.backup.BackupManager\$SelectTransportListenerWrapper\$1
android.app.backup.BackupManager\$SelectTransportListenerWrapper\$2
android.app.backup.BackupManager
android.app.backup.BackupManagerMonitor
android.app.backup.BackupObserver
android.app.backup.BackupTransport
android.app.backup.BackupUtils
android.app.backup.FileBackupHelperBase
android.app.backup.FullBackup\$BackupScheme\$PathWithRequiredFlags
android.app.backup.FullBackup\$BackupScheme
android.app.backup.FullBackup\$BackupSchemeId
android.app.backup.FullBackup
android.app.backup.FullBackupDataOutput
android.app.backup.RestoreObserver
android.app.backup.RestoreSession
android.app.backup.SelectBackupTransportCallback
android.app.blob.BlobStoreManager\$Session\$1\$\$ExternalSyntheticLambda0
android.app.blob.BlobStoreManager\$Session
android.app.blob.BlobStoreManager
android.app.blob.BlobStoreManagerFrameworkInitializer
android.app.blob.XmlTags
android.app.cloudsearch.CloudSearchManager\$CallBackWrapper\$\$ExternalSyntheticLambda0
android.app.cloudsearch.CloudSearchManager\$CallBackWrapper\$\$ExternalSyntheticLambda1
android.app.cloudsearch.CloudSearchManager
android.app.cloudsearch.SearchRequest\$Builder
android.app.cloudsearch.SearchResponse\$Builder
android.app.cloudsearch.SearchResult\$Builder
android.app.compat.ChangeIdStateQuery
android.app.compat.CompatChanges
android.app.compat.PackageOverride\$Builder
android.app.compat.PackageOverride
android.app.contentsuggestions.ClassificationsRequest\$Builder
android.app.contentsuggestions.ContentSuggestionsManager\$ClassificationsCallbackWrapper\$\$ExternalSyntheticLambda0
android.app.contentsuggestions.ContentSuggestionsManager\$SelectionsCallbackWrapper\$\$ExternalSyntheticLambda0
android.app.contentsuggestions.ContentSuggestionsManager
android.app.contentsuggestions.SelectionsRequest\$Builder
android.app.job.JobInfo\$Builder
android.app.job.JobProtoEnums
android.app.job.JobScheduler
android.app.job.JobSchedulerFrameworkInitializer
android.app.job.JobServiceEngine
android.app.people.ConversationStatus\$Builder
android.app.people.PeopleManager\$ConversationListener
android.app.people.PeopleManager\$ConversationListenerProxy\$\$ExternalSyntheticLambda0
android.app.people.PeopleManager
android.app.people.PeopleSpaceTile\$Builder
android.app.prediction.AppPredictionContext\$Builder
android.app.prediction.AppPredictionManager
android.app.prediction.AppPredictor\$\$ExternalSyntheticLambda0
android.app.prediction.AppPredictor\$CallbackWrapper\$\$ExternalSyntheticLambda0
android.app.prediction.AppPredictor
android.app.prediction.AppTarget\$Builder
android.app.prediction.AppTargetEvent\$Builder
android.app.search.SearchAction\$Builder
android.app.search.SearchSession\$CallbackWrapper\$\$ExternalSyntheticLambda0
android.app.search.SearchSession
android.app.search.SearchTarget\$Builder
android.app.search.SearchTargetEvent\$Builder
android.app.search.SearchUiManager
android.app.servertransaction.ObjectPool
android.app.servertransaction.PendingTransactionActions\$StopInfo
android.app.servertransaction.PendingTransactionActions
android.app.servertransaction.TransactionExecutor
android.app.servertransaction.TransactionExecutorHelper
android.app.settings.SettingsEnums
android.app.settings.mediaoutput.MediaOutputEnum
android.app.slice.Slice\$Builder
android.app.slice.SliceManager
android.app.slice.SliceMetrics
android.app.slice.SliceProvider\$\$ExternalSyntheticLambda0
android.app.slice.SliceQuery\$\$ExternalSyntheticLambda0
android.app.slice.SliceQuery\$\$ExternalSyntheticLambda1
android.app.slice.SliceQuery\$\$ExternalSyntheticLambda2
android.app.slice.SliceQuery\$1
android.app.slice.SliceQuery
android.app.smartspace.SmartspaceAction\$Builder
android.app.smartspace.SmartspaceConfig\$Builder
android.app.smartspace.SmartspaceManager
android.app.smartspace.SmartspaceSession\$\$ExternalSyntheticLambda0
android.app.smartspace.SmartspaceSession\$CallbackWrapper\$\$ExternalSyntheticLambda0
android.app.smartspace.SmartspaceSession
android.app.smartspace.SmartspaceTarget\$Builder
android.app.smartspace.SmartspaceTargetEvent\$Builder
android.app.smartspace.SmartspaceUtils
android.app.smartspace.uitemplatedata.BaseTemplateData\$Builder
android.app.smartspace.uitemplatedata.BaseTemplateData\$SubItemInfo\$Builder
android.app.smartspace.uitemplatedata.BaseTemplateData\$SubItemLoggingInfo\$Builder
android.app.smartspace.uitemplatedata.CarouselTemplateData\$CarouselItem\$Builder
android.app.smartspace.uitemplatedata.Icon\$Builder
android.app.smartspace.uitemplatedata.TapAction\$Builder
android.app.smartspace.uitemplatedata.Text\$Builder
android.app.tare.EconomyManager
android.app.time.Capabilities
android.app.time.GeolocationTimeZoneSuggestionProto
android.app.time.LocationTimeZoneManager
android.app.time.LocationTimeZoneManagerProto
android.app.time.LocationTimeZoneManagerServiceStateProto
android.app.time.MetricsTimeZoneSuggestion
android.app.time.TimeCapabilities\$Builder
android.app.time.TimeConfiguration\$Builder
android.app.time.TimeManager\$\$ExternalSyntheticLambda1
android.app.time.TimeManager
android.app.time.TimeZoneCapabilities\$Builder
android.app.time.TimeZoneConfiguration\$Builder
android.app.time.TimeZoneProviderStateProto
android.app.timedetector.TelephonyTimeSuggestion\$Builder
android.app.timedetector.TimeDetector
android.app.timezone.Callback
android.app.timezone.RulesManager\$CallbackWrapper\$\$ExternalSyntheticLambda0
android.app.timezone.RulesManager
android.app.timezone.RulesUpdaterContract
android.app.timezone.Utils
android.app.timezonedetector.TelephonyTimeZoneSuggestion\$Builder
android.app.timezonedetector.TimeZoneDetector
android.app.trust.TrustManager
android.app.tvsettings.TvSettingsEnums
android.app.usage.CacheQuotaHint\$Builder
android.app.usage.EventList
android.app.usage.StorageStatsManager
android.app.usage.UsageEvents\$Event
android.app.usage.UsageStats\$Builder
android.app.usage.UsageStatsManager
android.app.wallpapereffectsgeneration.CameraAttributes\$Builder
android.app.wallpapereffectsgeneration.CinematicEffectResponse\$Builder
android.app.wallpapereffectsgeneration.TexturedMesh\$Builder
android.app.wallpapereffectsgeneration.WallpaperEffectsGenerationManager\$CinematicEffectListenerWrapper\$\$ExternalSyntheticLambda0
android.app.wallpapereffectsgeneration.WallpaperEffectsGenerationManager
android.app.wearsettings.WearSettingsEnums
android.app.ActionBar\$LayoutParams\$InspectionCompanion
android.app.Activity\$\$ExternalSyntheticLambda0
android.app.Activity\$1
android.app.ActivityClient\$1
android.app.ActivityClient\$ActivityClientControllerSingleton
android.app.ActivityManager\$1
android.app.ActivityManager\$MemoryInfo\$1
android.app.ActivityManager\$MemoryInfo
android.app.ActivityManager\$PendingIntentInfo\$1
android.app.ActivityManager\$PendingIntentInfo
android.app.ActivityManager\$ProcessErrorStateInfo\$1
android.app.ActivityManager\$ProcessErrorStateInfo
android.app.ActivityManager\$RecentTaskInfo\$1
android.app.ActivityManager\$RecentTaskInfo
android.app.ActivityManager\$RunningAppProcessInfo\$1
android.app.ActivityManager\$RunningAppProcessInfo
android.app.ActivityManager\$RunningServiceInfo\$1
android.app.ActivityManager\$RunningServiceInfo
android.app.ActivityManager\$RunningTaskInfo\$1
android.app.ActivityManager\$RunningTaskInfo
android.app.ActivityManager\$TaskDescription\$1
android.app.ActivityManager\$TaskDescription
android.app.ActivityOptions\$SourceInfo\$1
android.app.ActivityOptions\$SourceInfo
android.app.ActivityOptions
android.app.ActivityTaskManager\$1
android.app.ActivityTaskManager\$2
android.app.ActivityTaskManager\$RootTaskInfo\$1
android.app.ActivityTaskManager\$RootTaskInfo
android.app.ActivityThread\$\$ExternalSyntheticLambda0
android.app.ActivityThread\$\$ExternalSyntheticLambda1
android.app.ActivityThread\$1
android.app.ActivityThread\$ActivityClientRecord\$1
android.app.ActivityThread\$ApplicationThread\$\$ExternalSyntheticLambda0
android.app.ActivityThread\$ApplicationThread\$\$ExternalSyntheticLambda1
android.app.ActivityThread\$GcIdler
android.app.ActivityThread\$H
android.app.ActivityThread\$Idler
android.app.ActivityThread\$PurgeIdler
android.app.ActivityThread\$ReceiverData
android.app.ActivityThread
android.app.ActivityTransitionCoordinator\$FixedEpicenterCallback
android.app.ActivityTransitionCoordinator\$GhostViewListeners
android.app.AlarmManager\$AlarmClockInfo\$1
android.app.AlarmManager\$AlarmClockInfo
android.app.AppOpsManager\$\$ExternalSyntheticLambda0
android.app.AppOpsManager\$\$ExternalSyntheticLambda4
android.app.AppOpsManager\$\$ExternalSyntheticLambda5
android.app.AppOpsManager\$1
android.app.AppOpsManager\$AppOpsCollector
android.app.AppOpsManager\$AttributedHistoricalOps\$1
android.app.AppOpsManager\$AttributedHistoricalOps
android.app.AppOpsManager\$AttributedOpEntry\$1
android.app.AppOpsManager\$AttributedOpEntry\$LongSparseArrayParceling
android.app.AppOpsManager\$AttributedOpEntry
android.app.AppOpsManager\$HistoricalOp\$1
android.app.AppOpsManager\$HistoricalOp
android.app.AppOpsManager\$HistoricalOps\$1
android.app.AppOpsManager\$HistoricalOps
android.app.AppOpsManager\$HistoricalPackageOps\$1
android.app.AppOpsManager\$HistoricalPackageOps
android.app.AppOpsManager\$HistoricalUidOps\$1
android.app.AppOpsManager\$HistoricalUidOps
android.app.AppOpsManager\$NoteOpEvent\$1
android.app.AppOpsManager\$NoteOpEvent
android.app.AppOpsManager\$OnOpActiveChangedInternalListener
android.app.AppOpsManager\$OnOpChangedInternalListener
android.app.AppOpsManager\$OpEntry\$1
android.app.AppOpsManager\$OpEntry
android.app.AppOpsManager\$OpEventProxyInfo\$1
android.app.AppOpsManager\$OpEventProxyInfo
android.app.AppOpsManager\$PackageOps\$1
android.app.AppOpsManager\$PackageOps
android.app.ApplicationErrorReport\$1
android.app.ApplicationErrorReport\$ParcelableCrashInfo\$1
android.app.ApplicationErrorReport\$ParcelableCrashInfo
android.app.ApplicationErrorReport
android.app.ApplicationExitInfo\$1
android.app.ApplicationExitInfo
android.app.ApplicationPackageManager\$1
android.app.ApplicationPackageManager\$3
android.app.ApplicationPackageManager
android.app.AsyncNotedAppOp\$1
android.app.AsyncNotedAppOp
android.app.AuthenticationRequiredException\$1
android.app.AuthenticationRequiredException
android.app.AutomaticZenRule\$1
android.app.AutomaticZenRule
android.app.BackStackRecord
android.app.BackStackState\$1
android.app.BackStackState
android.app.BackgroundServiceStartNotAllowedException\$1
android.app.BackgroundServiceStartNotAllowedException
android.app.BroadcastOptions
android.app.ContentProviderHolder\$1
android.app.ContentProviderHolder
android.app.ContextImpl
android.app.DatePickerDialog\$1
android.app.Dialog\$\$ExternalSyntheticLambda1
android.app.Dialog\$\$ExternalSyntheticLambda2
android.app.Dialog\$ListenersHandler
android.app.Dialog
android.app.DirectAction\$1
android.app.DirectAction
android.app.DisabledWallpaperManager
android.app.EnterTransitionCoordinator\$1
android.app.EnterTransitionCoordinator\$3
android.app.ExitTransitionCoordinator\$3
android.app.ExitTransitionCoordinator\$4
android.app.ExitTransitionCoordinator\$8
android.app.ExitTransitionCoordinator\$ActivityExitTransitionCallbacks
android.app.ForegroundServiceStartNotAllowedException\$1
android.app.ForegroundServiceStartNotAllowedException
android.app.Fragment\$1
android.app.Fragment\$InstantiationException
android.app.Fragment\$SavedState
android.app.FragmentBreadCrumbs\$1
android.app.FragmentHostCallback
android.app.FragmentManagerImpl\$AnimateOnHWLayerIfNeededListener
android.app.FragmentManagerImpl\$PopBackStackState
android.app.FragmentManagerImpl\$StartEnterTransitionListener
android.app.FragmentManagerState\$1
android.app.FragmentManagerState
android.app.FragmentState\$1
android.app.FragmentState
android.app.FragmentTransition\$2
android.app.FragmentTransition\$3
android.app.FragmentTransition\$4
android.app.GameModeInfo\$1
android.app.GameModeInfo
android.app.GameState\$1
android.app.GameState
android.app.GrantedUriPermission\$1
android.app.GrantedUriPermission
android.app.HomeVisibilityListener\$1\$\$ExternalSyntheticLambda1
android.app.InstantAppResolverService\$ServiceHandler
android.app.Instrumentation\$ActivityGoing
android.app.Instrumentation\$Idler
android.app.IntentReceiverLeaked
android.app.IntentService\$ServiceHandler
android.app.JobSchedulerImpl
android.app.LauncherActivity\$1
android.app.LauncherActivity\$ActivityAdapter\$ArrayFilter
android.app.ListActivity\$2
android.app.ListFragment\$2
android.app.LoadedApk\$ReceiverDispatcher\$Args
android.app.LoadedApk\$ServiceDispatcher\$DeathMonitor
android.app.LoadedApk\$SplitDependencyLoaderImpl
android.app.LoaderManagerImpl\$LoaderInfo
android.app.LoaderManagerImpl
android.app.MediaRouteActionProvider
android.app.Notification\$\$ExternalSyntheticLambda0
android.app.Notification\$1
android.app.Notification\$Action\$1
android.app.Notification\$Action\$WearableExtender
android.app.Notification\$Action
android.app.Notification\$BigPictureStyle
android.app.Notification\$BigTextStyle
android.app.Notification\$BubbleMetadata\$1
android.app.Notification\$BubbleMetadata
android.app.Notification\$CallStyle
android.app.Notification\$CarExtender
android.app.Notification\$DecoratedCustomViewStyle
android.app.Notification\$InboxStyle
android.app.Notification\$MediaStyle
android.app.Notification\$MessagingStyle
android.app.Notification\$TvExtender
android.app.Notification\$WearableExtender
android.app.Notification
android.app.NotificationChannel\$1
android.app.NotificationChannel
android.app.NotificationChannelGroup\$1
android.app.NotificationChannelGroup
android.app.NotificationHistory\$1
android.app.NotificationHistory
android.app.NotificationManager\$Policy\$1
android.app.NotificationManager\$Policy
android.app.PendingIntent\$1
android.app.PendingIntent\$CanceledException
android.app.PendingIntent
android.app.Person\$1
android.app.Person
android.app.PictureInPictureParams\$1
android.app.PictureInPictureParams
android.app.PictureInPictureUiState\$1
android.app.PictureInPictureUiState
android.app.Presentation\$1
android.app.ProcessMemoryState\$1
android.app.ProcessMemoryState
android.app.ProfilerInfo\$1
android.app.ProfilerInfo
android.app.ProgressDialog\$1
android.app.PropertyInvalidatedCache\$AutoCorker\$1
android.app.PropertyInvalidatedCache\$DefaultComputer
android.app.QueuedWork\$QueuedWorkHandler
android.app.RecoverableSecurityException\$1
android.app.RecoverableSecurityException\$LocalDialog\$\$ExternalSyntheticLambda0
android.app.RecoverableSecurityException
android.app.RemoteAction\$1
android.app.RemoteAction
android.app.RemoteInput\$1
android.app.RemoteInput
android.app.RemoteInputHistoryItem\$1
android.app.RemoteInputHistoryItem
android.app.RemoteServiceException
android.app.ResultInfo\$1
android.app.ResultInfo
android.app.RuntimeAppOpAccessMessage\$1
android.app.RuntimeAppOpAccessMessage
android.app.SearchDialog\$1
android.app.SearchDialog\$2
android.app.SearchDialog\$3
android.app.SearchDialog\$4
android.app.SearchDialog\$5
android.app.SearchManager
android.app.SearchableInfo\$1
android.app.SearchableInfo\$ActionKeyInfo
android.app.SearchableInfo
android.app.ServiceConnectionLeaked
android.app.ServiceStartArgs\$1
android.app.ServiceStartArgs
android.app.SharedElementCallback\$1
android.app.SharedPreferencesImpl\$EditorImpl
android.app.SharedPreferencesImpl
android.app.SyncNotedAppOp\$1
android.app.SyncNotedAppOp
android.app.SystemServiceRegistry\$29
android.app.SystemServiceRegistry\$CachedServiceFetcher
android.app.SystemServiceRegistry\$StaticServiceFetcher
android.app.TimePickerDialog\$1
android.app.UiAutomation\$IAccessibilityServiceClientImpl\$1
android.app.UiModeManager\$InnerListener\$\$ExternalSyntheticLambda0
android.app.UriGrantsManager\$1
android.app.VoiceInteractor\$1
android.app.VoiceInteractor\$AbortVoiceRequest
android.app.VoiceInteractor\$CommandRequest
android.app.VoiceInteractor\$CompleteVoiceRequest
android.app.VoiceInteractor\$ConfirmationRequest
android.app.VoiceInteractor\$PickOptionRequest\$Option\$1
android.app.VoiceInteractor\$PickOptionRequest\$Option
android.app.VoiceInteractor\$PickOptionRequest
android.app.VoiceInteractor\$Prompt\$1
android.app.VoiceInteractor\$Prompt
android.app.Vr2dDisplayProperties\$1
android.app.Vr2dDisplayProperties
android.app.WaitResult\$1
android.app.WaitResult
android.app.WallpaperColors\$1
android.app.WallpaperColors
android.app.WallpaperInfo\$1
android.app.WallpaperInfo
android.app.WallpaperManager\$FastBitmapDrawable
android.app.WallpaperManager\$Globals\$\$ExternalSyntheticLambda2
android.app.WindowConfiguration\$1
android.app.WindowConfiguration
android.app.admin.ConnectEvent\$1
android.app.admin.DelegatedAdminReceiver
android.app.admin.DeviceAdminInfo\$1
android.app.admin.DeviceAdminInfo
android.app.admin.DeviceAdminReceiver
android.app.admin.DevicePolicyCache\$EmptyDevicePolicyCache
android.app.admin.DevicePolicyDrawableResource\$1
android.app.admin.DevicePolicyDrawableResource
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda10
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda11
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda1
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda5
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda6
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda7
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda8
android.app.admin.DevicePolicyManager\$\$ExternalSyntheticLambda9
android.app.admin.DevicePolicyStringResource\$1
android.app.admin.DevicePolicyStringResource
android.app.admin.DeviceStateCache\$EmptyDeviceStateCache
android.app.admin.DnsEvent\$1
android.app.admin.FactoryResetProtectionPolicy\$1
android.app.admin.FactoryResetProtectionPolicy
android.app.admin.FullyManagedDeviceProvisioningParams\$1
android.app.admin.FullyManagedDeviceProvisioningParams
android.app.admin.ManagedProfileProvisioningParams\$1
android.app.admin.ManagedProfileProvisioningParams
android.app.admin.NetworkEvent\$1
android.app.admin.NetworkEvent
android.app.admin.ParcelableGranteeMap\$1
android.app.admin.ParcelableGranteeMap
android.app.admin.ParcelableResource\$1
android.app.admin.ParcelableResource
android.app.admin.PasswordMetrics\$1
android.app.admin.PasswordMetrics\$ComplexityBucket\$1
android.app.admin.PasswordMetrics\$ComplexityBucket\$2
android.app.admin.PasswordMetrics\$ComplexityBucket\$3
android.app.admin.PasswordMetrics\$ComplexityBucket\$4
android.app.admin.PasswordMetrics
android.app.admin.PreferentialNetworkServiceConfig\$1
android.app.admin.PreferentialNetworkServiceConfig
android.app.admin.ProvisioningException
android.app.admin.SecurityLog\$SecurityEvent\$1
android.app.admin.SecurityLog\$SecurityEvent
android.app.admin.SystemUpdateInfo\$1
android.app.admin.SystemUpdateInfo
android.app.admin.SystemUpdatePolicy\$1
android.app.admin.SystemUpdatePolicy\$ValidationFailedException\$1
android.app.admin.SystemUpdatePolicy\$ValidationFailedException
android.app.admin.SystemUpdatePolicy
android.app.admin.UnsafeStateException\$1
android.app.admin.UnsafeStateException
android.app.admin.WifiSsidPolicy\$1
android.app.admin.WifiSsidPolicy
android.app.ambientcontext.AmbientContextEvent\$1
android.app.ambientcontext.AmbientContextEvent
android.app.ambientcontext.AmbientContextEventRequest\$1
android.app.ambientcontext.AmbientContextEventRequest
android.app.ambientcontext.AmbientContextManager\$\$ExternalSyntheticLambda1
android.app.ambientcontext.AmbientContextManager\$\$ExternalSyntheticLambda3
android.app.assist.ActivityId\$1
android.app.assist.ActivityId
android.app.assist.AssistContent\$1
android.app.assist.AssistContent
android.app.assist.AssistStructure\$1
android.app.assist.AssistStructure\$HtmlInfoNode\$1
android.app.assist.AssistStructure\$HtmlInfoNode
android.app.assist.AssistStructure\$HtmlInfoNodeBuilder
android.app.assist.AssistStructure\$ViewNodeBuilder
android.app.assist.AssistStructure\$ViewNodeParcelable\$1
android.app.assist.AssistStructure\$ViewNodeParcelable
android.app.assist.AssistStructure
android.app.backup.AbsoluteFileBackupHelper
android.app.backup.BackupManager\$BackupObserverWrapper\$1
android.app.backup.BackupProgress\$1
android.app.backup.BackupProgress
android.app.backup.BlobBackupHelper
android.app.backup.FileBackupHelper
android.app.backup.RestoreDescription\$1
android.app.backup.RestoreDescription
android.app.backup.RestoreSession\$RestoreObserverWrapper\$1
android.app.backup.RestoreSet\$1
android.app.backup.RestoreSet
android.app.backup.SharedPreferencesBackupHelper
android.app.backup.WallpaperBackupHelper
android.app.blob.BlobHandle\$1
android.app.blob.BlobHandle
android.app.blob.BlobInfo\$1
android.app.blob.BlobInfo
android.app.blob.BlobStoreManager\$\$ExternalSyntheticLambda0
android.app.blob.BlobStoreManagerFrameworkInitializer\$\$ExternalSyntheticLambda0
android.app.blob.LeaseInfo\$1
android.app.blob.LeaseInfo
android.app.cloudsearch.SearchRequest\$1
android.app.cloudsearch.SearchRequest
android.app.cloudsearch.SearchResponse\$1
android.app.cloudsearch.SearchResponse
android.app.cloudsearch.SearchResult\$1
android.app.cloudsearch.SearchResult
android.app.compat.ChangeIdStateCache
android.app.contentsuggestions.ClassificationsRequest\$1
android.app.contentsuggestions.ClassificationsRequest
android.app.contentsuggestions.ContentClassification\$1
android.app.contentsuggestions.ContentClassification
android.app.contentsuggestions.ContentSelection\$1
android.app.contentsuggestions.ContentSelection
android.app.contentsuggestions.SelectionsRequest\$1
android.app.contentsuggestions.SelectionsRequest
android.app.job.JobInfo\$1
android.app.job.JobInfo\$TriggerContentUri\$1
android.app.job.JobInfo\$TriggerContentUri
android.app.job.JobInfo
android.app.job.JobParameters\$1
android.app.job.JobParameters
android.app.job.JobSchedulerFrameworkInitializer\$\$ExternalSyntheticLambda0
android.app.job.JobSchedulerFrameworkInitializer\$\$ExternalSyntheticLambda1
android.app.job.JobSchedulerFrameworkInitializer\$\$ExternalSyntheticLambda2
android.app.job.JobSchedulerFrameworkInitializer\$\$ExternalSyntheticLambda3
android.app.job.JobSchedulerFrameworkInitializer\$\$ExternalSyntheticLambda4
android.app.job.JobService\$1
android.app.job.JobServiceEngine\$JobHandler
android.app.job.JobSnapshot\$1
android.app.job.JobSnapshot
android.app.job.JobWorkItem\$1
android.app.job.JobWorkItem
android.app.people.ConversationChannel\$1
android.app.people.ConversationChannel
android.app.people.ConversationStatus\$1
android.app.people.ConversationStatus
android.app.people.PeopleSpaceTile\$1
android.app.people.PeopleSpaceTile
android.app.prediction.AppPredictionContext\$1
android.app.prediction.AppPredictionContext
android.app.prediction.AppPredictionSessionId\$1
android.app.prediction.AppPredictionSessionId
android.app.prediction.AppTarget\$1
android.app.prediction.AppTarget
android.app.prediction.AppTargetEvent\$1
android.app.prediction.AppTargetEvent
android.app.prediction.AppTargetId\$1
android.app.prediction.AppTargetId
android.app.search.Query\$1
android.app.search.Query
android.app.search.SearchAction\$1
android.app.search.SearchAction
android.app.search.SearchContext\$1
android.app.search.SearchContext
android.app.search.SearchSessionId\$1
android.app.search.SearchSessionId
android.app.search.SearchTarget\$1
android.app.search.SearchTarget
android.app.search.SearchTargetEvent\$1
android.app.search.SearchTargetEvent
android.app.servertransaction.ActivityConfigurationChangeItem\$1
android.app.servertransaction.ActivityRelaunchItem\$1
android.app.servertransaction.ActivityResultItem\$1
android.app.servertransaction.BaseClientRequest
android.app.servertransaction.ClientTransaction\$1
android.app.servertransaction.ClientTransaction
android.app.servertransaction.ConfigurationChangeItem\$1
android.app.servertransaction.DestroyActivityItem\$1
android.app.servertransaction.EnterPipRequestedItem\$1
android.app.servertransaction.LaunchActivityItem\$1
android.app.servertransaction.MoveToDisplayItem\$1
android.app.servertransaction.NewIntentItem\$1
android.app.servertransaction.PauseActivityItem\$1
android.app.servertransaction.PipStateTransactionItem\$1
android.app.servertransaction.ResumeActivityItem\$1
android.app.servertransaction.StartActivityItem\$1
android.app.servertransaction.StopActivityItem\$1
android.app.servertransaction.TopResumedActivityChangeItem\$1
android.app.servertransaction.TransferSplashScreenViewStateItem\$1
android.app.slice.Slice\$1
android.app.slice.Slice
android.app.slice.SliceItem\$1
android.app.slice.SliceItem
android.app.slice.SliceSpec\$1
android.app.slice.SliceSpec
android.app.smartspace.SmartspaceAction\$1
android.app.smartspace.SmartspaceAction
android.app.smartspace.SmartspaceConfig\$1
android.app.smartspace.SmartspaceConfig
android.app.smartspace.SmartspaceSessionId\$1
android.app.smartspace.SmartspaceSessionId
android.app.smartspace.SmartspaceTarget\$1
android.app.smartspace.SmartspaceTarget
android.app.smartspace.SmartspaceTargetEvent\$1
android.app.smartspace.SmartspaceTargetEvent
android.app.smartspace.uitemplatedata.BaseTemplateData\$1
android.app.smartspace.uitemplatedata.BaseTemplateData\$SubItemInfo\$1
android.app.smartspace.uitemplatedata.BaseTemplateData\$SubItemInfo
android.app.smartspace.uitemplatedata.BaseTemplateData\$SubItemLoggingInfo\$1
android.app.smartspace.uitemplatedata.BaseTemplateData\$SubItemLoggingInfo
android.app.smartspace.uitemplatedata.BaseTemplateData
android.app.smartspace.uitemplatedata.CarouselTemplateData\$1
android.app.smartspace.uitemplatedata.CarouselTemplateData\$Builder
android.app.smartspace.uitemplatedata.CarouselTemplateData\$CarouselItem\$1
android.app.smartspace.uitemplatedata.CarouselTemplateData\$CarouselItem
android.app.smartspace.uitemplatedata.CombinedCardsTemplateData\$1
android.app.smartspace.uitemplatedata.CombinedCardsTemplateData\$Builder
android.app.smartspace.uitemplatedata.HeadToHeadTemplateData\$1
android.app.smartspace.uitemplatedata.HeadToHeadTemplateData\$Builder
android.app.smartspace.uitemplatedata.Icon\$1
android.app.smartspace.uitemplatedata.Icon
android.app.smartspace.uitemplatedata.SubCardTemplateData\$1
android.app.smartspace.uitemplatedata.SubCardTemplateData\$Builder
android.app.smartspace.uitemplatedata.SubImageTemplateData\$1
android.app.smartspace.uitemplatedata.SubImageTemplateData\$Builder
android.app.smartspace.uitemplatedata.SubListTemplateData\$1
android.app.smartspace.uitemplatedata.SubListTemplateData\$Builder
android.app.smartspace.uitemplatedata.TapAction\$1
android.app.smartspace.uitemplatedata.TapAction
android.app.smartspace.uitemplatedata.Text\$1
android.app.smartspace.uitemplatedata.Text
android.app.time.ExternalTimeSuggestion\$1
android.app.time.ExternalTimeSuggestion
android.app.time.TimeCapabilities\$1
android.app.time.TimeCapabilities
android.app.time.TimeCapabilitiesAndConfig\$1
android.app.time.TimeCapabilitiesAndConfig
android.app.time.TimeConfiguration\$1
android.app.time.TimeConfiguration
android.app.time.TimeManager\$\$ExternalSyntheticLambda0
android.app.time.TimeZoneCapabilities\$1
android.app.time.TimeZoneCapabilities
android.app.time.TimeZoneCapabilitiesAndConfig\$1
android.app.time.TimeZoneCapabilitiesAndConfig
android.app.time.TimeZoneConfiguration\$1
android.app.time.TimeZoneConfiguration
android.app.timedetector.GnssTimeSuggestion\$1
android.app.timedetector.GnssTimeSuggestion
android.app.timedetector.ManualTimeSuggestion\$1
android.app.timedetector.ManualTimeSuggestion
android.app.timedetector.NetworkTimeSuggestion\$1
android.app.timedetector.NetworkTimeSuggestion
android.app.timedetector.TelephonyTimeSuggestion\$1
android.app.timedetector.TelephonyTimeSuggestion
android.app.timedetector.TimeDetectorImpl
android.app.timezone.DistroFormatVersion\$1
android.app.timezone.DistroFormatVersion
android.app.timezone.DistroRulesVersion\$1
android.app.timezone.DistroRulesVersion
android.app.timezone.RulesState\$1
android.app.timezone.RulesState
android.app.timezonedetector.ManualTimeZoneSuggestion\$1
android.app.timezonedetector.ManualTimeZoneSuggestion
android.app.timezonedetector.TelephonyTimeZoneSuggestion\$1
android.app.timezonedetector.TelephonyTimeZoneSuggestion
android.app.timezonedetector.TimeZoneDetectorImpl
android.app.trust.TrustManager\$2
android.app.usage.AppLaunchEstimateInfo\$1
android.app.usage.AppLaunchEstimateInfo
android.app.usage.AppStandbyInfo\$1
android.app.usage.AppStandbyInfo
android.app.usage.BroadcastResponseStats\$1
android.app.usage.BroadcastResponseStats
android.app.usage.BroadcastResponseStatsList\$1
android.app.usage.BroadcastResponseStatsList
android.app.usage.CacheQuotaHint\$1
android.app.usage.CacheQuotaHint
android.app.usage.CacheQuotaService\$ServiceHandler
android.app.usage.ConfigurationStats\$1
android.app.usage.ConfigurationStats
android.app.usage.EventStats\$1
android.app.usage.EventStats
android.app.usage.ExternalStorageStats\$1
android.app.usage.ExternalStorageStats
android.app.usage.StorageStats\$1
android.app.usage.StorageStats
android.app.usage.TimeSparseArray
android.app.usage.UsageEvents\$1
android.app.usage.UsageEvents
android.app.usage.UsageStats\$1
android.app.usage.UsageStats
android.app.wallpapereffectsgeneration.CameraAttributes\$1
android.app.wallpapereffectsgeneration.CameraAttributes
android.app.wallpapereffectsgeneration.CinematicEffectRequest\$1
android.app.wallpapereffectsgeneration.CinematicEffectRequest
android.app.wallpapereffectsgeneration.CinematicEffectResponse\$1
android.app.wallpapereffectsgeneration.CinematicEffectResponse
android.app.wallpapereffectsgeneration.TexturedMesh\$1
android.app.wallpapereffectsgeneration.TexturedMesh
android.app.ActionBar\$LayoutParams
android.app.Activity\$HostCallbacks
android.app.ActivityTransitionCoordinator\$ContinueTransitionListener
android.app.ActivityTransitionCoordinator
android.app.AlertDialog
android.app.Application
android.app.ContextImpl\$ApplicationContentResolver
android.app.DownloadManager\$CursorTranslator
android.app.EnterTransitionCoordinator\$4
android.app.EnterTransitionCoordinator\$6
android.app.EnterTransitionCoordinator\$7
android.app.EnterTransitionCoordinator\$8
android.app.ExitTransitionCoordinator\$2
android.app.ExitTransitionCoordinator\$5
android.app.Fragment\$SavedState\$1
android.app.Fragment
android.app.FragmentManagerImpl\$2
android.app.FragmentManagerImpl\$3
android.app.FragmentManagerImpl
android.app.FragmentTransition\$1
android.app.FragmentTransition\$5
android.app.IActivityClientController\$Default
android.app.IActivityClientController\$Stub\$Proxy
android.app.IActivityClientController\$Stub
android.app.IActivityController\$Default
android.app.IActivityController\$Stub\$Proxy
android.app.IActivityController\$Stub
android.app.IActivityManager\$Default
android.app.IActivityManager\$Stub\$Proxy
android.app.IActivityManager\$Stub
android.app.IActivityPendingResult\$Default
android.app.IActivityPendingResult\$Stub\$Proxy
android.app.IActivityPendingResult\$Stub
android.app.IActivityTaskManager\$Default
android.app.IActivityTaskManager\$Stub\$Proxy
android.app.IActivityTaskManager\$Stub
android.app.IAlarmCompleteListener\$Default
android.app.IAlarmCompleteListener\$Stub\$Proxy
android.app.IAlarmCompleteListener\$Stub
android.app.IAlarmListener\$Default
android.app.IAlarmListener\$Stub\$Proxy
android.app.IAlarmListener\$Stub
android.app.IAlarmManager\$Default
android.app.IAlarmManager\$Stub\$Proxy
android.app.IAlarmManager\$Stub
android.app.IAppTask\$Default
android.app.IAppTask\$Stub\$Proxy
android.app.IAppTask\$Stub
android.app.IAppTraceRetriever\$Default
android.app.IAppTraceRetriever\$Stub\$Proxy
android.app.IAppTraceRetriever\$Stub
android.app.IApplicationThread\$Default
android.app.IApplicationThread\$Stub\$Proxy
android.app.IApplicationThread\$Stub
android.app.IAssistDataReceiver\$Default
android.app.IAssistDataReceiver\$Stub\$Proxy
android.app.IAssistDataReceiver\$Stub
android.app.IBackupAgent\$Default
android.app.IBackupAgent\$Stub\$Proxy
android.app.IBackupAgent\$Stub
android.app.ICompatCameraControlCallback\$Default
android.app.ICompatCameraControlCallback\$Stub\$Proxy
android.app.ICompatCameraControlCallback\$Stub
android.app.IEphemeralResolver\$Default
android.app.IEphemeralResolver\$Stub\$Proxy
android.app.IEphemeralResolver\$Stub
android.app.IForegroundServiceObserver\$Default
android.app.IForegroundServiceObserver\$Stub\$Proxy
android.app.IForegroundServiceObserver\$Stub
android.app.IGameManager\$Default
android.app.IGameManager\$Stub\$Proxy
android.app.IGameManager\$Stub
android.app.IGameManagerService\$Default
android.app.IGameManagerService\$Stub\$Proxy
android.app.IGameManagerService\$Stub
android.app.IInstantAppResolver\$Default
android.app.IInstantAppResolver\$Stub\$Proxy
android.app.IInstantAppResolver\$Stub
android.app.IInstrumentationWatcher\$Default
android.app.IInstrumentationWatcher\$Stub\$Proxy
android.app.IInstrumentationWatcher\$Stub
android.app.ILocalWallpaperColorConsumer\$Default
android.app.ILocalWallpaperColorConsumer\$Stub\$Proxy
android.app.ILocalWallpaperColorConsumer\$Stub
android.app.ILocaleManager\$Default
android.app.ILocaleManager\$Stub\$Proxy
android.app.ILocaleManager\$Stub
android.app.INotificationManager\$Default
android.app.INotificationManager\$Stub\$Proxy
android.app.INotificationManager\$Stub
android.app.IOnProjectionStateChangedListener\$Default
android.app.IOnProjectionStateChangedListener\$Stub\$Proxy
android.app.IOnProjectionStateChangedListener\$Stub
android.app.IParcelFileDescriptorRetriever\$Default
android.app.IParcelFileDescriptorRetriever\$Stub\$Proxy
android.app.IParcelFileDescriptorRetriever\$Stub
android.app.IProcessObserver\$Default
android.app.IProcessObserver\$Stub\$Proxy
android.app.IProcessObserver\$Stub
android.app.IRequestFinishCallback\$Default
android.app.IRequestFinishCallback\$Stub\$Proxy
android.app.IRequestFinishCallback\$Stub
android.app.ISearchManager\$Default
android.app.ISearchManager\$Stub\$Proxy
android.app.ISearchManager\$Stub
android.app.ISearchManagerCallback\$Default
android.app.ISearchManagerCallback\$Stub\$Proxy
android.app.ISearchManagerCallback\$Stub
android.app.IServiceConnection\$Default
android.app.IServiceConnection\$Stub\$Proxy
android.app.IServiceConnection\$Stub
android.app.IStopUserCallback\$Default
android.app.IStopUserCallback\$Stub\$Proxy
android.app.IStopUserCallback\$Stub
android.app.ITaskStackListener\$Default
android.app.ITaskStackListener\$Stub\$Proxy
android.app.ITaskStackListener\$Stub
android.app.ITransientNotification\$Default
android.app.ITransientNotification\$Stub\$Proxy
android.app.ITransientNotification\$Stub
android.app.ITransientNotificationCallback\$Default
android.app.ITransientNotificationCallback\$Stub\$Proxy
android.app.ITransientNotificationCallback\$Stub
android.app.IUiAutomationConnection\$Default
android.app.IUiAutomationConnection\$Stub\$Proxy
android.app.IUiAutomationConnection\$Stub
android.app.IUiModeManager\$Default
android.app.IUiModeManager\$Stub\$Proxy
android.app.IUiModeManager\$Stub
android.app.IUidObserver\$Default
android.app.IUidObserver\$Stub\$Proxy
android.app.IUidObserver\$Stub
android.app.IUriGrantsManager\$Default
android.app.IUriGrantsManager\$Stub\$Proxy
android.app.IUriGrantsManager\$Stub
android.app.IUserSwitchObserver\$Default
android.app.IUserSwitchObserver\$Stub\$Proxy
android.app.IUserSwitchObserver\$Stub
android.app.IWallpaperManager\$Default
android.app.IWallpaperManager\$Stub\$Proxy
android.app.IWallpaperManager\$Stub
android.app.IWallpaperManagerCallback\$Default
android.app.IWallpaperManagerCallback\$Stub\$Proxy
android.app.IWallpaperManagerCallback\$Stub
android.app.IWindowToken\$Default
android.app.IWindowToken\$Stub\$Proxy
android.app.IWindowToken\$Stub
android.app.LocalActivityManager\$LocalActivityRecord
android.app.MediaRouteActionProvider\$MediaRouterCallback
android.app.MediaRouteButton\$MediaRouterCallback
android.app.MediaRouteButton
android.app.NativeActivity\$NativeContentView
android.app.Notification\$BuilderRemoteViews
android.app.Notification\$DecoratedMediaCustomViewStyle
android.app.Presentation
android.app.ReceiverRestrictedContext
android.app.RemoteServiceException\$BadForegroundServiceNotificationException
android.app.RemoteServiceException\$CannotDeliverBroadcastException
android.app.RemoteServiceException\$CannotPostForegroundServiceNotificationException
android.app.RemoteServiceException\$CrashedByAdbException
android.app.RemoteServiceException\$ForegroundServiceDidNotStartInTimeException
android.app.RemoteServiceException\$MissingRequestPasswordComplexityPermissionException
android.app.ResourcesManager\$UpdateHandler
android.app.SearchDialog
android.app.Service
android.app.SystemServiceRegistry\$100
android.app.SystemServiceRegistry\$101
android.app.SystemServiceRegistry\$102
android.app.SystemServiceRegistry\$103
android.app.SystemServiceRegistry\$104
android.app.SystemServiceRegistry\$105
android.app.SystemServiceRegistry\$106
android.app.SystemServiceRegistry\$107
android.app.SystemServiceRegistry\$108
android.app.SystemServiceRegistry\$109
android.app.SystemServiceRegistry\$10
android.app.SystemServiceRegistry\$110
android.app.SystemServiceRegistry\$111
android.app.SystemServiceRegistry\$112
android.app.SystemServiceRegistry\$113
android.app.SystemServiceRegistry\$114
android.app.SystemServiceRegistry\$115
android.app.SystemServiceRegistry\$116
android.app.SystemServiceRegistry\$117
android.app.SystemServiceRegistry\$118
android.app.SystemServiceRegistry\$119
android.app.SystemServiceRegistry\$11
android.app.SystemServiceRegistry\$120
android.app.SystemServiceRegistry\$121
android.app.SystemServiceRegistry\$122
android.app.SystemServiceRegistry\$123
android.app.SystemServiceRegistry\$124
android.app.SystemServiceRegistry\$125
android.app.SystemServiceRegistry\$126
android.app.SystemServiceRegistry\$127
android.app.SystemServiceRegistry\$128
android.app.SystemServiceRegistry\$129
android.app.SystemServiceRegistry\$12
android.app.SystemServiceRegistry\$130
android.app.SystemServiceRegistry\$131
android.app.SystemServiceRegistry\$132
android.app.SystemServiceRegistry\$133
android.app.SystemServiceRegistry\$134
android.app.SystemServiceRegistry\$135
android.app.SystemServiceRegistry\$136
android.app.SystemServiceRegistry\$137
android.app.SystemServiceRegistry\$13
android.app.SystemServiceRegistry\$14
android.app.SystemServiceRegistry\$15
android.app.SystemServiceRegistry\$16
android.app.SystemServiceRegistry\$17
android.app.SystemServiceRegistry\$18
android.app.SystemServiceRegistry\$19
android.app.SystemServiceRegistry\$1
android.app.SystemServiceRegistry\$20
android.app.SystemServiceRegistry\$21
android.app.SystemServiceRegistry\$22
android.app.SystemServiceRegistry\$23
android.app.SystemServiceRegistry\$24
android.app.SystemServiceRegistry\$25
android.app.SystemServiceRegistry\$26
android.app.SystemServiceRegistry\$27
android.app.SystemServiceRegistry\$28
android.app.SystemServiceRegistry\$2
android.app.SystemServiceRegistry\$30
android.app.SystemServiceRegistry\$31
android.app.SystemServiceRegistry\$32
android.app.SystemServiceRegistry\$33
android.app.SystemServiceRegistry\$34
android.app.SystemServiceRegistry\$35
android.app.SystemServiceRegistry\$36
android.app.SystemServiceRegistry\$37
android.app.SystemServiceRegistry\$38
android.app.SystemServiceRegistry\$39
android.app.SystemServiceRegistry\$3
android.app.SystemServiceRegistry\$40
android.app.SystemServiceRegistry\$41
android.app.SystemServiceRegistry\$42
android.app.SystemServiceRegistry\$43
android.app.SystemServiceRegistry\$44
android.app.SystemServiceRegistry\$45
android.app.SystemServiceRegistry\$46
android.app.SystemServiceRegistry\$47
android.app.SystemServiceRegistry\$48
android.app.SystemServiceRegistry\$49
android.app.SystemServiceRegistry\$4
android.app.SystemServiceRegistry\$50
android.app.SystemServiceRegistry\$51
android.app.SystemServiceRegistry\$52
android.app.SystemServiceRegistry\$53
android.app.SystemServiceRegistry\$54
android.app.SystemServiceRegistry\$55
android.app.SystemServiceRegistry\$56
android.app.SystemServiceRegistry\$57
android.app.SystemServiceRegistry\$58
android.app.SystemServiceRegistry\$59
android.app.SystemServiceRegistry\$5
android.app.SystemServiceRegistry\$60
android.app.SystemServiceRegistry\$61
android.app.SystemServiceRegistry\$62
android.app.SystemServiceRegistry\$63
android.app.SystemServiceRegistry\$64
android.app.SystemServiceRegistry\$65
android.app.SystemServiceRegistry\$66
android.app.SystemServiceRegistry\$67
android.app.SystemServiceRegistry\$68
android.app.SystemServiceRegistry\$69
android.app.SystemServiceRegistry\$6
android.app.SystemServiceRegistry\$70
android.app.SystemServiceRegistry\$71
android.app.SystemServiceRegistry\$72
android.app.SystemServiceRegistry\$73
android.app.SystemServiceRegistry\$74
android.app.SystemServiceRegistry\$75
android.app.SystemServiceRegistry\$76
android.app.SystemServiceRegistry\$77
android.app.SystemServiceRegistry\$78
android.app.SystemServiceRegistry\$79
android.app.SystemServiceRegistry\$7
android.app.SystemServiceRegistry\$80
android.app.SystemServiceRegistry\$81
android.app.SystemServiceRegistry\$82
android.app.SystemServiceRegistry\$83
android.app.SystemServiceRegistry\$84
android.app.SystemServiceRegistry\$85
android.app.SystemServiceRegistry\$86
android.app.SystemServiceRegistry\$87
android.app.SystemServiceRegistry\$88
android.app.SystemServiceRegistry\$89
android.app.SystemServiceRegistry\$8
android.app.SystemServiceRegistry\$90
android.app.SystemServiceRegistry\$91
android.app.SystemServiceRegistry\$92
android.app.SystemServiceRegistry\$93
android.app.SystemServiceRegistry\$94
android.app.SystemServiceRegistry\$95
android.app.SystemServiceRegistry\$96
android.app.SystemServiceRegistry\$97
android.app.SystemServiceRegistry\$98
android.app.SystemServiceRegistry\$99
android.app.SystemServiceRegistry\$9
android.app.admin.ConnectEvent
android.app.admin.DnsEvent
android.app.admin.IDeviceAdminService\$Default
android.app.admin.IDeviceAdminService\$Stub\$Proxy
android.app.admin.IDeviceAdminService\$Stub
android.app.admin.IDevicePolicyManager\$Default
android.app.admin.IDevicePolicyManager\$Stub\$Proxy
android.app.admin.IDevicePolicyManager\$Stub
android.app.admin.IKeyguardCallback\$Default
android.app.admin.IKeyguardCallback\$Stub\$Proxy
android.app.admin.IKeyguardCallback\$Stub
android.app.admin.IKeyguardClient\$Default
android.app.admin.IKeyguardClient\$Stub\$Proxy
android.app.admin.IKeyguardClient\$Stub
android.app.admin.StartInstallingUpdateCallback\$Default
android.app.admin.StartInstallingUpdateCallback\$Stub\$Proxy
android.app.admin.StartInstallingUpdateCallback\$Stub
android.app.ambientcontext.IAmbientContextManager\$Default
android.app.ambientcontext.IAmbientContextManager\$Stub\$Proxy
android.app.ambientcontext.IAmbientContextManager\$Stub
android.app.assist.AssistStructure\$ParcelTransferWriter
android.app.assist.AssistStructure\$SendChannel
android.app.backup.BackupAgent
android.app.backup.IBackupCallback\$Default
android.app.backup.IBackupCallback\$Stub\$Proxy
android.app.backup.IBackupCallback\$Stub
android.app.backup.IBackupManager\$Default
android.app.backup.IBackupManager\$Stub\$Proxy
android.app.backup.IBackupManager\$Stub
android.app.backup.IBackupManagerMonitor\$Default
android.app.backup.IBackupManagerMonitor\$Stub\$Proxy
android.app.backup.IBackupManagerMonitor\$Stub
android.app.backup.IBackupObserver\$Default
android.app.backup.IBackupObserver\$Stub\$Proxy
android.app.backup.IBackupObserver\$Stub
android.app.backup.IFullBackupRestoreObserver\$Default
android.app.backup.IFullBackupRestoreObserver\$Stub\$Proxy
android.app.backup.IFullBackupRestoreObserver\$Stub
android.app.backup.IRestoreObserver\$Default
android.app.backup.IRestoreObserver\$Stub\$Proxy
android.app.backup.IRestoreObserver\$Stub
android.app.backup.IRestoreSession\$Default
android.app.backup.IRestoreSession\$Stub\$Proxy
android.app.backup.IRestoreSession\$Stub
android.app.backup.ISelectBackupTransportCallback\$Default
android.app.backup.ISelectBackupTransportCallback\$Stub\$Proxy
android.app.backup.ISelectBackupTransportCallback\$Stub
android.app.blob.IBlobCommitCallback\$Default
android.app.blob.IBlobCommitCallback\$Stub\$Proxy
android.app.blob.IBlobCommitCallback\$Stub
android.app.blob.IBlobStoreManager\$Default
android.app.blob.IBlobStoreManager\$Stub\$Proxy
android.app.blob.IBlobStoreManager\$Stub
android.app.blob.IBlobStoreSession\$Default
android.app.blob.IBlobStoreSession\$Stub\$Proxy
android.app.blob.IBlobStoreSession\$Stub
android.app.cloudsearch.ICloudSearchManager\$Default
android.app.cloudsearch.ICloudSearchManager\$Stub\$Proxy
android.app.cloudsearch.ICloudSearchManager\$Stub
android.app.cloudsearch.ICloudSearchManagerCallback\$Default
android.app.cloudsearch.ICloudSearchManagerCallback\$Stub\$Proxy
android.app.cloudsearch.ICloudSearchManagerCallback\$Stub
android.app.contentsuggestions.IClassificationsCallback\$Default
android.app.contentsuggestions.IClassificationsCallback\$Stub\$Proxy
android.app.contentsuggestions.IClassificationsCallback\$Stub
android.app.contentsuggestions.IContentSuggestionsManager\$Default
android.app.contentsuggestions.IContentSuggestionsManager\$Stub\$Proxy
android.app.contentsuggestions.IContentSuggestionsManager\$Stub
android.app.contentsuggestions.ISelectionsCallback\$Default
android.app.contentsuggestions.ISelectionsCallback\$Stub\$Proxy
android.app.contentsuggestions.ISelectionsCallback\$Stub
android.app.job.IJobCallback\$Default
android.app.job.IJobCallback\$Stub\$Proxy
android.app.job.IJobCallback\$Stub
android.app.job.IJobScheduler\$Default
android.app.job.IJobScheduler\$Stub\$Proxy
android.app.job.IJobScheduler\$Stub
android.app.job.IJobService\$Default
android.app.job.IJobService\$Stub\$Proxy
android.app.job.IJobService\$Stub
android.app.people.IConversationListener\$Default
android.app.people.IConversationListener\$Stub\$Proxy
android.app.people.IConversationListener\$Stub
android.app.people.IPeopleManager\$Default
android.app.people.IPeopleManager\$Stub\$Proxy
android.app.people.IPeopleManager\$Stub
android.app.prediction.IPredictionCallback\$Default
android.app.prediction.IPredictionCallback\$Stub\$Proxy
android.app.prediction.IPredictionCallback\$Stub
android.app.prediction.IPredictionManager\$Default
android.app.prediction.IPredictionManager\$Stub\$Proxy
android.app.prediction.IPredictionManager\$Stub
android.app.search.ISearchCallback\$Default
android.app.search.ISearchCallback\$Stub\$Proxy
android.app.search.ISearchCallback\$Stub
android.app.search.ISearchUiManager\$Default
android.app.search.ISearchUiManager\$Stub\$Proxy
android.app.search.ISearchUiManager\$Stub
android.app.servertransaction.ClientTransactionItem
android.app.slice.ISliceListener\$Default
android.app.slice.ISliceListener\$Stub\$Proxy
android.app.slice.ISliceListener\$Stub
android.app.slice.ISliceManager\$Default
android.app.slice.ISliceManager\$Stub\$Proxy
android.app.slice.ISliceManager\$Stub
android.app.smartspace.ISmartspaceCallback\$Default
android.app.smartspace.ISmartspaceCallback\$Stub\$Proxy
android.app.smartspace.ISmartspaceCallback\$Stub
android.app.smartspace.ISmartspaceManager\$Default
android.app.smartspace.ISmartspaceManager\$Stub\$Proxy
android.app.smartspace.ISmartspaceManager\$Stub
android.app.smartspace.uitemplatedata.CarouselTemplateData
android.app.smartspace.uitemplatedata.CombinedCardsTemplateData
android.app.smartspace.uitemplatedata.HeadToHeadTemplateData
android.app.smartspace.uitemplatedata.SubCardTemplateData
android.app.smartspace.uitemplatedata.SubImageTemplateData
android.app.smartspace.uitemplatedata.SubListTemplateData
android.app.tare.IEconomyManager\$Default
android.app.tare.IEconomyManager\$Stub\$Proxy
android.app.tare.IEconomyManager\$Stub
android.app.time.ITimeZoneDetectorListener\$Default
android.app.time.ITimeZoneDetectorListener\$Stub\$Proxy
android.app.time.ITimeZoneDetectorListener\$Stub
android.app.timedetector.ITimeDetectorService\$Default
android.app.timedetector.ITimeDetectorService\$Stub\$Proxy
android.app.timedetector.ITimeDetectorService\$Stub
android.app.timezone.ICallback\$Default
android.app.timezone.ICallback\$Stub\$Proxy
android.app.timezone.ICallback\$Stub
android.app.timezone.IRulesManager\$Default
android.app.timezone.IRulesManager\$Stub\$Proxy
android.app.timezone.IRulesManager\$Stub
android.app.timezonedetector.ITimeZoneDetectorService\$Default
android.app.timezonedetector.ITimeZoneDetectorService\$Stub\$Proxy
android.app.timezonedetector.ITimeZoneDetectorService\$Stub
android.app.trust.IStrongAuthTracker\$Default
android.app.trust.IStrongAuthTracker\$Stub\$Proxy
android.app.trust.IStrongAuthTracker\$Stub
android.app.trust.ITrustListener\$Default
android.app.trust.ITrustListener\$Stub\$Proxy
android.app.trust.ITrustListener\$Stub
android.app.trust.ITrustManager\$Default
android.app.trust.ITrustManager\$Stub\$Proxy
android.app.trust.ITrustManager\$Stub
android.app.usage.ICacheQuotaService\$Default
android.app.usage.ICacheQuotaService\$Stub\$Proxy
android.app.usage.ICacheQuotaService\$Stub
android.app.usage.IStorageStatsManager\$Default
android.app.usage.IStorageStatsManager\$Stub\$Proxy
android.app.usage.IStorageStatsManager\$Stub
android.app.usage.IUsageStatsManager\$Default
android.app.usage.IUsageStatsManager\$Stub\$Proxy
android.app.usage.IUsageStatsManager\$Stub
android.app.wallpapereffectsgeneration.ICinematicEffectListener\$Default
android.app.wallpapereffectsgeneration.ICinematicEffectListener\$Stub\$Proxy
android.app.wallpapereffectsgeneration.ICinematicEffectListener\$Stub
android.app.wallpapereffectsgeneration.IWallpaperEffectsGenerationManager\$Default
android.app.wallpapereffectsgeneration.IWallpaperEffectsGenerationManager\$Stub\$Proxy
android.app.wallpapereffectsgeneration.IWallpaperEffectsGenerationManager\$Stub
android.app.Activity\$RequestFinishCallback
android.app.Activity
android.app.ActivityManager\$UidObserver
android.app.ActivityOptions\$1
android.app.ActivityOptions\$2
android.app.ActivityThread\$2
android.app.ActivityThread\$ApplicationThread
android.app.ActivityThread\$SafeCancellationTransport
android.app.AlarmManager\$ListenerWrapper
android.app.AppOpsManager\$2
android.app.AppOpsManager\$3
android.app.AppOpsManager\$4
android.app.AppOpsManager\$5
android.app.AppOpsManager\$OnOpNotedCallback\$1
android.app.ApplicationPackageManager\$2
android.app.ApplicationPackageManager\$DexModuleRegisterCallbackDelegate
android.app.ApplicationPackageManager\$MoveCallbackDelegate
android.app.DatePickerDialog
android.app.DialogFragment
android.app.EnterTransitionCoordinator\$5
android.app.EnterTransitionCoordinator
android.app.ExitTransitionCoordinator\$6
android.app.ExitTransitionCoordinator\$7
android.app.ExitTransitionCoordinator
android.app.FragmentBreadCrumbs
android.app.HomeVisibilityListener\$1
android.app.InstantAppResolverService\$1
android.app.InstantAppResolverService
android.app.IntentService
android.app.KeyguardManager\$1
android.app.KeyguardManager\$2
android.app.KeyguardManager\$3
android.app.KeyguardManager\$4
android.app.KeyguardManager\$5
android.app.LauncherActivity\$ActivityAdapter
android.app.ListFragment
android.app.LoadedApk\$ReceiverDispatcher\$InnerReceiver
android.app.LoadedApk\$ServiceDispatcher\$InnerConnection
android.app.PackageDeleteObserver\$1
android.app.PackageInstallObserver\$1
android.app.PendingIntent\$CancelListerInfo
android.app.PendingIntent\$FinishedDispatcher
android.app.ProgressDialog
android.app.StatusBarManager\$NearbyMediaDevicesProviderWrapper
android.app.StatusBarManager\$RequestResultCallback
android.app.StatusBarManager\$UndoCallback
android.app.TaskStackListener
android.app.TimePickerDialog
android.app.UiAutomationConnection
android.app.UiModeManager\$InnerListener
android.app.UserSwitchObserver
android.app.VoiceInteractor\$2
android.app.VoiceInteractor\$KillCallback
android.app.VrManager\$CallbackEntry\$1
android.app.VrManager\$CallbackEntry\$2
android.app.WallpaperManager\$Globals\$1
android.app.WallpaperManager\$Globals
android.app.WallpaperManager\$WallpaperSetCompletion
android.app.admin.DeviceAdminService\$IDeviceAdminServiceImpl
android.app.admin.DeviceAdminService
android.app.admin.DevicePolicyKeyguardService\$1
android.app.admin.DevicePolicyKeyguardService
android.app.admin.DevicePolicyManager\$1
android.app.admin.DevicePolicyManager\$2
android.app.backup.BackupAgent\$BackupServiceBinder
android.app.backup.BackupAgentHelper
android.app.backup.BackupManager\$BackupManagerMonitorWrapper
android.app.backup.BackupManager\$BackupObserverWrapper
android.app.backup.BackupManager\$SelectTransportListenerWrapper
android.app.backup.BackupTransport\$TransportImpl
android.app.backup.FullBackupAgent
android.app.backup.RestoreSession\$BackupManagerMonitorWrapper
android.app.backup.RestoreSession\$RestoreObserverWrapper
android.app.blob.BlobStoreManager\$Session\$1
android.app.cloudsearch.CloudSearchManager\$CallBackWrapper
android.app.contentsuggestions.ContentSuggestionsManager\$ClassificationsCallbackWrapper
android.app.contentsuggestions.ContentSuggestionsManager\$SelectionsCallbackWrapper
android.app.job.JobService
android.app.job.JobServiceEngine\$JobInterface
android.app.people.PeopleManager\$ConversationListenerProxy
android.app.prediction.AppPredictor\$CallbackWrapper
android.app.search.SearchSession\$CallbackWrapper
android.app.servertransaction.ActivityTransactionItem
android.app.servertransaction.ConfigurationChangeItem
android.app.servertransaction.LaunchActivityItem
android.app.slice.SliceProvider
android.app.smartspace.SmartspaceSession\$CallbackWrapper
android.app.time.TimeManager\$1
android.app.timezone.RulesManager\$CallbackWrapper
android.app.trust.TrustManager\$1
android.app.usage.CacheQuotaService\$CacheQuotaServiceWrapper
android.app.usage.CacheQuotaService
android.app.wallpapereffectsgeneration.WallpaperEffectsGenerationManager\$CinematicEffectListenerWrapper
android.app.ActivityGroup
android.app.AliasActivity
android.app.AppDetailsActivity
android.app.ExpandableListActivity
android.app.ListActivity
android.app.NativeActivity
android.app.RecoverableSecurityException\$LocalDialog
android.app.SearchDialog\$SearchBar
android.app.SynchronousUserSwitchObserver
android.app.UiAutomation\$IAccessibilityServiceClientImpl
android.app.servertransaction.ActivityConfigurationChangeItem
android.app.servertransaction.ActivityLifecycleItem
android.app.servertransaction.ActivityRelaunchItem
android.app.servertransaction.ActivityResultItem
android.app.servertransaction.EnterPipRequestedItem
android.app.servertransaction.MoveToDisplayItem
android.app.servertransaction.NewIntentItem
android.app.servertransaction.PipStateTransactionItem
android.app.servertransaction.TopResumedActivityChangeItem
android.app.servertransaction.TransferSplashScreenViewStateItem
android.app.LauncherActivity
android.app.TabActivity
android.app.servertransaction.DestroyActivityItem
android.app.servertransaction.PauseActivityItem
android.app.servertransaction.ResumeActivityItem
android.app.servertransaction.StartActivityItem
android.app.servertransaction.StopActivityItem " | parallel -j 12 python3 OffsetAnalysis.py {}  app-class/{}_result.txt