mkdir content-class
echo "android.content.AbstractThreadedSyncAdapter\$ISyncAdapterImpl\$\$ExternalSyntheticLambda0
android.content.AbstractThreadedSyncAdapter\$ISyncAdapterImpl_IA
android.content.AbstractThreadedSyncAdapter\$SyncThread_IA
android.content.AbstractThreadedSyncAdapter\$SyncThread
android.content.AbstractThreadedSyncAdapter
android.content.ActivityInfoProto
android.content.ActivityNotFoundException
android.content.ApexEnvironment
android.content.AsyncQueryHandler\$WorkerArgs
android.content.Attributable
android.content.AttributionSource\$Builder
android.content.AttributionSource\$ScopedParcelState
android.content.AuthorityEntryProto
android.content.BroadcastReceiver\$PendingResult\$1
android.content.BroadcastReceiver\$PendingResult
android.content.BroadcastReceiver
android.content.ClipData\$Item
android.content.ClipDataProto\$Icon
android.content.ClipDataProto\$Item
android.content.ClipDataProto
android.content.ClipDescription\$ClassificationStatus
android.content.ClipDescriptionProto
android.content.ClipboardManager\$1\$\$ExternalSyntheticLambda0
android.content.ClipboardManager\$OnPrimaryClipChangedListener
android.content.ComponentCallbacks2\$TrimMemoryLevel
android.content.ComponentCallbacks
android.content.ComponentCallbacksController\$\$ExternalSyntheticLambda0
android.content.ComponentCallbacksController\$\$ExternalSyntheticLambda1
android.content.ComponentCallbacksController\$\$ExternalSyntheticLambda2
android.content.ComponentCallbacksController
android.content.ComponentName\$WithComponentName
android.content.ComponentNameProto
android.content.ConfigurationProto
android.content.ContentInsertHandler
android.content.ContentInterface
android.content.ContentProvider\$CallingIdentity
android.content.ContentProvider\$PipeDataWriter
android.content.ContentProviderClient\$NotRespondingRunnable_IA
android.content.ContentProviderClient\$NotRespondingRunnable
android.content.ContentProviderOperation\$BackReference_IA
android.content.ContentProviderOperation\$Builder_IA
android.content.ContentProviderOperation\$Builder
android.content.ContentProviderOperation_IA
android.content.ContentQueryMap
android.content.ContentResolver\$\$ExternalSyntheticLambda0
android.content.ContentResolver\$\$ExternalSyntheticLambda1
android.content.ContentResolver\$MimeTypeInfo
android.content.ContentResolver\$NotifyFlags
android.content.ContentResolver\$OpenResourceIdResult
android.content.ContentResolver\$QueryCollator
android.content.ContentResolver\$ResultListener_IA
android.content.ContentResolver\$SortDirection
android.content.ContentResolver\$StringResultListener_IA
android.content.ContentResolver\$SyncExemption
android.content.ContentResolver\$UriResultListener_IA
android.content.ContentUris
android.content.ContentValues_IA
android.content.Context\$BindServiceFlags
android.content.Context\$CreatePackageOptions
android.content.Context\$DatabaseMode
android.content.Context\$FileMode
android.content.Context\$PreferencesMode
android.content.Context\$RegisterReceiverFlags
android.content.Context\$ServiceName
android.content.Context
android.content.ContextParams\$Builder
android.content.ContextParams_IA
android.content.ContextParams
android.content.DeviceConfigurationProto
android.content.DialogInterface\$OnCancelListener
android.content.DialogInterface\$OnClickListener
android.content.DialogInterface\$OnDismissListener
android.content.DialogInterface\$OnKeyListener
android.content.DialogInterface\$OnMultiChoiceClickListener
android.content.DialogInterface\$OnShowListener
android.content.DialogInterface
android.content.Entity\$NamedContentValues
android.content.Entity
android.content.EntityIterator
android.content.EventLogTags
android.content.GlobalConfigurationProto
android.content.Intent\$AccessUriMode
android.content.Intent\$CommandOptionHandler
android.content.Intent\$CopyMode
android.content.Intent\$FillInFlags
android.content.Intent\$FilterComparison
android.content.Intent\$Flags
android.content.Intent\$GrantUriMode
android.content.Intent\$MutableFlags
android.content.Intent\$UriFlags
android.content.IntentFilter\$\$ExternalSyntheticLambda0
android.content.IntentFilter\$\$ExternalSyntheticLambda1
android.content.IntentFilter\$\$ExternalSyntheticLambda2
android.content.IntentFilter\$\$ExternalSyntheticLambda3
android.content.IntentFilter\$AuthorityEntry
android.content.IntentFilter\$InstantAppVisibility
android.content.IntentFilterProto
android.content.IntentProto
android.content.IntentSender\$OnFinished
android.content.Loader\$OnLoadCanceledListener
android.content.Loader\$OnLoadCompleteListener
android.content.Loader
android.content.LocaleProto
android.content.LocusIdProto
android.content.LoggingContentInterface\$Logger
android.content.MimeTypeFilter
android.content.OperationApplicationException
android.content.PeriodicSync_IA
android.content.PermissionChecker
android.content.QuickViewConstants
android.content.ResourcesConfigurationProto
android.content.RestrictionsManager
android.content.ServiceConnection
android.content.SharedPreferences\$Editor
android.content.SharedPreferences\$OnSharedPreferenceChangeListener
android.content.SharedPreferences
android.content.SyncContext
android.content.SyncRequest\$Builder
android.content.SyncRequest_IA
android.content.SyncResult_IA
android.content.SyncStatusInfo\$Stats
android.content.SyncStatusObserver
android.content.UndoManager\$UndoState
android.content.UndoManager
android.content.UndoOwner
android.content.UriMatcher
android.content.integrity.AppInstallMetadata\$Builder
android.content.integrity.AppInstallMetadata_IA
android.content.integrity.AppInstallMetadata
android.content.integrity.AppIntegrityManager
android.content.integrity.AtomicFormula\$Key
android.content.integrity.AtomicFormula\$Operator
android.content.integrity.CompoundFormula\$\$ExternalSyntheticLambda0
android.content.integrity.CompoundFormula\$\$ExternalSyntheticLambda1
android.content.integrity.CompoundFormula\$\$ExternalSyntheticLambda2
android.content.integrity.CompoundFormula\$\$ExternalSyntheticLambda3
android.content.integrity.CompoundFormula\$\$ExternalSyntheticLambda4
android.content.integrity.CompoundFormula\$Connector
android.content.integrity.InstallerAllowedByManifestFormula_IA
android.content.integrity.IntegrityFormula\$Application
android.content.integrity.IntegrityFormula\$Installer
android.content.integrity.IntegrityFormula\$SourceStamp
android.content.integrity.IntegrityFormula\$Tag
android.content.integrity.IntegrityFormula
android.content.integrity.IntegrityUtils
android.content.integrity.Rule\$Effect
android.content.integrity.RuleSet\$Builder
android.content.integrity.RuleSet_IA
android.content.integrity.RuleSet
android.content.om.CriticalOverlayInfo
android.content.om.FabricatedOverlay\$Builder
android.content.om.FabricatedOverlay_IA
android.content.om.FabricatedOverlay
android.content.om.IOverlayManager\$Stub\$\$ExternalSyntheticLambda0
android.content.om.IOverlayManager\$Stub\$Proxy\$\$ExternalSyntheticLambda0
android.content.om.OverlayInfo\$State
android.content.om.OverlayManager
android.content.om.OverlayManagerTransaction\$Builder
android.content.om.OverlayManagerTransaction\$Request\$RequestType
android.content.om.OverlayManagerTransaction\$Request
android.content.om.OverlayManagerTransaction_IA
android.content.om.OverlayableInfo
android.content.pm.ActivityInfo\$ColorMode
android.content.pm.ActivityInfo\$Config
android.content.pm.ActivityInfo\$LaunchMode
android.content.pm.ActivityInfo\$ScreenOrientation
android.content.pm.ActivityInfo\$SizeChangesSupportMode
android.content.pm.ActivityInfo\$WindowLayout
android.content.pm.ActivityInfo_IA
android.content.pm.ActivityPresentationInfo
android.content.pm.AndroidTestBaseUpdater
android.content.pm.AppSearchShortcutInfo\$\$ExternalSyntheticLambda0
android.content.pm.AppSearchShortcutInfo\$\$ExternalSyntheticLambda1
android.content.pm.AppSearchShortcutInfo\$\$ExternalSyntheticLambda2
android.content.pm.AppSearchShortcutInfo\$\$ExternalSyntheticLambda3
android.content.pm.AppSearchShortcutInfo\$\$ExternalSyntheticLambda4
android.content.pm.AppSearchShortcutInfo\$Builder\$\$ExternalSyntheticLambda0
android.content.pm.AppSearchShortcutInfo\$Builder\$\$ExternalSyntheticLambda1
android.content.pm.AppSearchShortcutInfo\$Builder\$\$ExternalSyntheticLambda2
android.content.pm.AppSearchShortcutInfo\$Builder\$\$ExternalSyntheticLambda3
android.content.pm.AppSearchShortcutInfo\$Builder\$\$ExternalSyntheticLambda4
android.content.pm.AppSearchShortcutInfo\$Builder
android.content.pm.AppSearchShortcutInfo
android.content.pm.AppSearchShortcutPerson\$Builder
android.content.pm.AppSearchShortcutPerson
android.content.pm.ApplicationInfo\$ApplicationInfoPrivateFlags
android.content.pm.ApplicationInfo\$ApplicationInfoPrivateFlagsExt
android.content.pm.ApplicationInfo\$Category
android.content.pm.ApplicationInfo\$DisplayNameComparator
android.content.pm.ApplicationInfo\$GwpAsanMode
android.content.pm.ApplicationInfo\$HiddenApiEnforcementPolicy
android.content.pm.ApplicationInfo\$MemtagMode
android.content.pm.ApplicationInfo\$NativeHeapZeroInitialized
android.content.pm.ApplicationInfo\$RawExternalStorage
android.content.pm.ApplicationInfo_IA
android.content.pm.ApplicationInfoProto\$Detail
android.content.pm.ApplicationInfoProto\$Version
android.content.pm.ApplicationInfoProto
android.content.pm.AppsQueryHelper
android.content.pm.AuxiliaryResolveInfo
android.content.pm.Capability\$Builder
android.content.pm.Capability_IA
android.content.pm.CapabilityParams\$Builder
android.content.pm.CapabilityParams_IA
android.content.pm.Checksum\$Type
android.content.pm.Checksum\$TypeMask
android.content.pm.ConfigurationInfo_IA
android.content.pm.ConstrainDisplayApisConfig
android.content.pm.CrossProfileApps\$\$ExternalSyntheticLambda0
android.content.pm.CrossProfileApps\$\$ExternalSyntheticLambda1
android.content.pm.CrossProfileApps
android.content.pm.CrossProfileAppsInternal
android.content.pm.DataLoaderManager
android.content.pm.DataLoaderParams
android.content.pm.DataLoaderType
android.content.pm.FallbackCategoryProvider
android.content.pm.FeatureInfo_IA
android.content.pm.FeatureInfoProto
android.content.pm.IPackageManager\$Stub\$\$ExternalSyntheticLambda0
android.content.pm.IPackageManager\$Stub\$Proxy\$\$ExternalSyntheticLambda0
android.content.pm.IncrementalStatesInfo_IA
android.content.pm.InstallSourceInfo_IA
android.content.pm.InstallationFile
android.content.pm.InstallationFileLocation
android.content.pm.InstantAppInfo_IA
android.content.pm.InstantAppRequest
android.content.pm.InstrumentationInfo_IA
android.content.pm.LauncherActivityInfo
android.content.pm.LauncherApps\$\$ExternalSyntheticLambda0
android.content.pm.LauncherApps\$AppUsageLimit_IA
android.content.pm.LauncherApps\$Callback
android.content.pm.LauncherApps\$CallbackMessageHandler\$CallbackInfo_IA
android.content.pm.LauncherApps\$CallbackMessageHandler\$CallbackInfo
android.content.pm.LauncherApps\$PinItemRequest\$RequestType
android.content.pm.LauncherApps\$PinItemRequest_IA
android.content.pm.LauncherApps\$ShortcutCacheFlags
android.content.pm.LauncherApps\$ShortcutChangeCallback
android.content.pm.LauncherApps\$ShortcutQuery\$QueryFlags
android.content.pm.LauncherApps\$ShortcutQuery
android.content.pm.LauncherApps
android.content.pm.LimitedLengthInputStream
android.content.pm.MacAuthenticatedInputStream
android.content.pm.ModuleInfo_IA
android.content.pm.PackageInfo_IA
android.content.pm.PackageInfoLite_IA
android.content.pm.PackageInstaller\$FileLocation
android.content.pm.PackageInstaller\$PackageSourceType
android.content.pm.PackageInstaller\$Session\$1\$\$ExternalSyntheticLambda0
android.content.pm.PackageInstaller\$Session
android.content.pm.PackageInstaller\$SessionCallback
android.content.pm.PackageInstaller\$SessionCallbackDelegate\$\$ExternalSyntheticLambda2
android.content.pm.PackageInstaller\$SessionCallbackDelegate\$\$ExternalSyntheticLambda4
android.content.pm.PackageInstaller\$SessionParams\$UserActionRequirement
android.content.pm.PackageInstaller
android.content.pm.PackageItemInfo\$DisplayNameComparator
android.content.pm.PackageItemInfo
android.content.pm.PackageItemInfoProto
android.content.pm.PackageManager\$ApplicationInfoFlagsBits
android.content.pm.PackageManager\$ApplicationInfoQuery
android.content.pm.PackageManager\$CertificateInputType
android.content.pm.PackageManager\$ComponentInfoFlagsBits
android.content.pm.PackageManager\$ComponentType
android.content.pm.PackageManager\$DeleteFlags
android.content.pm.PackageManager\$DexModuleRegisterCallback
android.content.pm.PackageManager\$DistractionRestriction
android.content.pm.PackageManager\$EnabledFlags
android.content.pm.PackageManager\$EnabledState
android.content.pm.PackageManager\$Flags
android.content.pm.PackageManager\$InstallFlags
android.content.pm.PackageManager\$InstallReason
android.content.pm.PackageManager\$InstallScenario
android.content.pm.PackageManager\$InstalledModulesFlags
android.content.pm.PackageManager\$InstrumentationInfoFlags
android.content.pm.PackageManager\$ModuleInfoFlags
android.content.pm.PackageManager\$MoveCallback
android.content.pm.PackageManager\$NotifyReason
android.content.pm.PackageManager\$OnChecksumsReadyListener
android.content.pm.PackageManager\$OnPermissionsChangedListener
android.content.pm.PackageManager\$PackageInfoFlagsBits
android.content.pm.PackageManager\$PackageInfoQuery
android.content.pm.PackageManager\$PermissionFlags
android.content.pm.PackageManager\$PermissionGroupInfoFlags
android.content.pm.PackageManager\$PermissionInfoFlags
android.content.pm.PackageManager\$PermissionResult
android.content.pm.PackageManager\$PermissionWhitelistFlags
android.content.pm.PackageManager\$PropertyLocation
android.content.pm.PackageManager\$ResolveInfoFlagsBits
android.content.pm.PackageManager\$RollbackDataPolicy
android.content.pm.PackageManager\$SignatureResult
android.content.pm.PackageManager\$SystemAppState
android.content.pm.PackageManager\$UninstallReason
android.content.pm.PackageManager
android.content.pm.PackageParser\$\$ExternalSyntheticLambda0
android.content.pm.PackageParser\$\$ExternalSyntheticLambda1
android.content.pm.PackageParser\$\$ExternalSyntheticLambda2
android.content.pm.PackageParser\$Activity_IA
android.content.pm.PackageParser\$ApkLite
android.content.pm.PackageParser\$CachedComponentArgs_IA
android.content.pm.PackageParser\$CachedComponentArgs
android.content.pm.PackageParser\$Callback
android.content.pm.PackageParser\$Component
android.content.pm.PackageParser\$Instrumentation_IA
android.content.pm.PackageParser\$NewPermissionInfo
android.content.pm.PackageParser\$PackageLite
android.content.pm.PackageParser\$PackageParserException
android.content.pm.PackageParser\$ParseFlags
android.content.pm.PackageParser\$ParsePackageItemArgs
android.content.pm.PackageParser\$Permission_IA
android.content.pm.PackageParser\$PermissionGroup_IA
android.content.pm.PackageParser\$Provider_IA
android.content.pm.PackageParser\$Service_IA
android.content.pm.PackageParser\$SigningDetails\$Builder
android.content.pm.PackageParser\$SigningDetails\$CertCapabilities
android.content.pm.PackageParser\$SigningDetails\$SignatureSchemeVersion
android.content.pm.PackageParser\$SplitAssetLoader
android.content.pm.PackageParser\$SplitDependencyLoader\$IllegalDependencyException_IA
android.content.pm.PackageParser\$SplitDependencyLoader\$IllegalDependencyException
android.content.pm.PackageParser\$SplitDependencyLoader
android.content.pm.PackageParser\$SplitNameComparator_IA
android.content.pm.PackageParser\$SplitNameComparator
android.content.pm.PackageParser
android.content.pm.PackageParserCacheHelper
android.content.pm.PackagePartitions\$DeferredCanonicalFile_IA
android.content.pm.PackagePartitions\$DeferredCanonicalFile
android.content.pm.PackagePartitions\$PartitionType
android.content.pm.PackagePartitions\$SystemPartition_IA
android.content.pm.PackagePartitions\$SystemPartition
android.content.pm.PackagePartitions
android.content.pm.ParceledListSlice_IA
android.content.pm.PermissionGroupInfo\$Flags
android.content.pm.PermissionGroupInfo_IA
android.content.pm.PermissionInfo\$Flags
android.content.pm.PermissionInfo\$Protection
android.content.pm.PermissionInfo\$ProtectionFlags
android.content.pm.PermissionInfo_IA
android.content.pm.ProviderInfo_IA
android.content.pm.ProviderInfoList_IA
android.content.pm.RegisteredServicesCache\$\$ExternalSyntheticLambda0
android.content.pm.RegisteredServicesCache\$ServiceInfo
android.content.pm.RegisteredServicesCache\$UserServices_IA
android.content.pm.RegisteredServicesCache\$UserServices
android.content.pm.RegisteredServicesCache
android.content.pm.RegisteredServicesCacheListener
android.content.pm.ResolveInfo\$DisplayNameComparator
android.content.pm.ResolveInfo_IA
android.content.pm.ServiceInfo\$ForegroundServiceType
android.content.pm.ServiceInfo_IA
android.content.pm.SharedLibraryInfo\$Type
android.content.pm.SharedLibraryInfo_IA
android.content.pm.ShortcutInfo\$\$ExternalSyntheticLambda0
android.content.pm.ShortcutInfo\$\$ExternalSyntheticLambda1
android.content.pm.ShortcutInfo\$Builder
android.content.pm.ShortcutInfo\$CloneFlags
android.content.pm.ShortcutInfo\$DisabledReason
android.content.pm.ShortcutInfo\$ShortcutFlags
android.content.pm.ShortcutInfo\$Surface
android.content.pm.ShortcutInfo_IA
android.content.pm.ShortcutManager\$ShareShortcutInfo_IA
android.content.pm.ShortcutManager\$ShortcutMatchFlags
android.content.pm.ShortcutManager
android.content.pm.ShortcutServiceInternal\$ShortcutChangeListener
android.content.pm.ShortcutServiceInternal
android.content.pm.Signature_IA
android.content.pm.SigningDetails\$Builder
android.content.pm.SigningDetails\$CapabilityMergeRule
android.content.pm.SigningDetails\$CertCapabilities
android.content.pm.SigningDetails\$SignatureSchemeVersion
android.content.pm.SigningInfo_IA
android.content.pm.StringParceledListSlice_IA
android.content.pm.SuspendDialogInfo\$Builder
android.content.pm.SuspendDialogInfo\$ButtonAction
android.content.pm.SuspendDialogInfo_IA
android.content.pm.UserInfo\$UserInfoFlag
android.content.pm.UserInfo_IA
android.content.pm.VerifierDeviceIdentity_IA
android.content.pm.VerifierInfo_IA
android.content.pm.VersionedPackage\$VersionCode
android.content.pm.VersionedPackage_IA
android.content.pm.XmlSerializerAndParser
android.content.pm.dex.ArtManager\$ProfileType
android.content.pm.dex.ArtManager\$SnapshotRuntimeProfileCallback
android.content.pm.dex.ArtManager\$SnapshotRuntimeProfileCallbackDelegate\$\$ExternalSyntheticLambda0
android.content.pm.dex.ArtManager\$SnapshotRuntimeProfileCallbackDelegate\$\$ExternalSyntheticLambda1
android.content.pm.dex.ArtManager\$SnapshotRuntimeProfileCallbackDelegate_IA
android.content.pm.dex.ArtManager
android.content.pm.dex.ArtManagerInternal
android.content.pm.dex.DexMetadataHelper
android.content.pm.dex.PackageOptimizationInfo
android.content.pm.overlay.OverlayPaths\$Builder
android.content.pm.overlay.OverlayPaths_IA
android.content.pm.overlay.OverlayPaths
android.content.pm.parsing.ApkLite
android.content.pm.parsing.ApkLiteParseUtils\$SplitNameComparator_IA
android.content.pm.parsing.ApkLiteParseUtils\$SplitNameComparator
android.content.pm.parsing.ApkLiteParseUtils
android.content.pm.parsing.FrameworkParsingPackageUtils
android.content.pm.parsing.PackageLite\$\$ExternalSyntheticLambda0
android.content.pm.parsing.PackageLite
android.content.pm.parsing.result.ParseInput\$Callback
android.content.pm.parsing.result.ParseInput\$DeferredError
android.content.pm.parsing.result.ParseInput
android.content.pm.parsing.result.ParseResult
android.content.pm.permission.RuntimePermissionPresentationInfo_IA
android.content.pm.pkg.FrameworkPackageUserState
android.content.pm.split.SplitDependencyLoader\$IllegalDependencyException_IA
android.content.pm.split.SplitDependencyLoader\$IllegalDependencyException
android.content.pm.split.SplitDependencyLoader
android.content.pm.verify.domain.DomainVerificationInfo\$State
android.content.pm.verify.domain.DomainVerificationManager\$\$ExternalSyntheticLambda0
android.content.pm.verify.domain.DomainVerificationManager\$Error
android.content.pm.verify.domain.DomainVerificationManager
android.content.pm.verify.domain.DomainVerificationState\$State
android.content.pm.verify.domain.DomainVerificationState
android.content.pm.verify.domain.DomainVerificationUserState\$DomainState
android.content.pm.verify.domain.DomainVerificationUtils
android.content.res.ApkAssets\$FormatType
android.content.res.ApkAssets\$PropertyFlags
android.content.res.ApkAssets
android.content.res.AssetManager\$AssetInputStream_IA
android.content.res.AssetManager\$AssetInputStream
android.content.res.AssetManager\$Builder
android.content.res.AssetManager_IA
android.content.res.AssetManager
android.content.res.CompatibilityInfo\$Translator
android.content.res.CompatibilityInfo_IA
android.content.res.ComplexColor
android.content.res.Configuration\$NativeConfig
android.content.res.Configuration\$Orientation
android.content.res.Configuration_IA
android.content.res.ConstantState
android.content.res.FontResourcesParser\$FamilyResourceEntry
android.content.res.FontResourcesParser\$FontFileResourceEntry
android.content.res.FontResourcesParser
android.content.res.GradientColor\$GradientTileMode
android.content.res.ObbInfo_IA
android.content.res.ObbScanner
android.content.res.ResourceId
android.content.res.Resources\$\$ExternalSyntheticLambda0
android.content.res.Resources\$\$ExternalSyntheticLambda1
android.content.res.Resources\$NotFoundException
android.content.res.Resources\$Theme_IA
android.content.res.Resources\$Theme
android.content.res.Resources\$ThemeKey
android.content.res.Resources
android.content.res.ResourcesImpl\$\$ExternalSyntheticLambda1
android.content.res.ResourcesImpl\$LookupStack_IA
android.content.res.ResourcesImpl\$LookupStack
android.content.res.ResourcesImpl\$ThemeImpl
android.content.res.ResourcesImpl
android.content.res.ResourcesKey
android.content.res.StringBlock\$StyleIDs
android.content.res.StringBlock
android.content.res.ThemedResourceCache
android.content.res.TypedArray
android.content.res.XmlBlock
android.content.res.loader.AssetsProvider
android.content.res.loader.ResourcesLoader\$UpdateCallbacks
android.content.res.loader.ResourcesLoader
android.content.res.loader.ResourcesProvider
android.content.rollback.PackageRollbackInfo\$RestoreInfo
android.content.rollback.PackageRollbackInfo_IA
android.content.rollback.RollbackInfo_IA
android.content.rollback.RollbackManager\$Status
android.content.rollback.RollbackManager
android.content.rollback.RollbackManagerFrameworkInitializer
android.content.type.DefaultMimeMapFactory\$\$ExternalSyntheticLambda0
android.content.type.DefaultMimeMapFactory
android.content.AsyncQueryHandler\$WorkerHandler
android.content.AsyncQueryHandler
android.content.AsyncTaskLoader\$LoadTask
android.content.AsyncTaskLoader
android.content.AttributionSource\$1
android.content.AttributionSource
android.content.AttributionSourceState\$1
android.content.AttributionSourceState
android.content.AutofillOptions\$1
android.content.AutofillOptions
android.content.ClipData\$1
android.content.ClipData
android.content.ClipDescription\$1
android.content.ClipDescription
android.content.ClipboardManager
android.content.ComponentCallbacks2
android.content.ComponentName\$1
android.content.ComponentName
android.content.ContentCaptureOptions\$1
android.content.ContentCaptureOptions
android.content.ContentProvider\$1
android.content.ContentProviderClient
android.content.ContentProviderOperation\$1
android.content.ContentProviderOperation\$BackReference\$1
android.content.ContentProviderOperation\$BackReference
android.content.ContentProviderOperation
android.content.ContentProviderResult\$1
android.content.ContentProviderResult
android.content.ContentQueryMap\$1
android.content.ContentResolver\$\$ExternalSyntheticLambda2
android.content.ContentResolver\$ResultListener
android.content.ContentResolver
android.content.ContentValues\$1
android.content.ContentValues
android.content.ContextWrapper
android.content.CursorEntityIterator
android.content.DefaultDataHandler
android.content.IClipboard
android.content.IContentProvider
android.content.IContentService
android.content.IIntentReceiver
android.content.IIntentSender
android.content.IOnPrimaryClipChangedListener
android.content.IRestrictionsManager
android.content.ISyncAdapter
android.content.ISyncAdapterUnsyncableAccountCallback
android.content.ISyncContext
android.content.ISyncServiceAdapter
android.content.ISyncStatusObserver
android.content.Intent\$1
android.content.Intent\$ShortcutIconResource\$1
android.content.Intent\$ShortcutIconResource
android.content.Intent
android.content.IntentFilter\$1
android.content.IntentFilter\$MalformedMimeTypeException
android.content.IntentFilter
android.content.IntentSender\$1
android.content.IntentSender\$SendIntentException
android.content.IntentSender
android.content.Loader\$ForceLoadContentObserver
android.content.LocusId\$1
android.content.LocusId
android.content.LoggingContentInterface
android.content.PeriodicSync\$1
android.content.PeriodicSync
android.content.ReceiverCallNotAllowedException
android.content.RestrictionEntry\$1
android.content.RestrictionEntry
android.content.SearchRecentSuggestionsProvider\$DatabaseHelper
android.content.SyncAdapterType\$1
android.content.SyncAdapterType
android.content.SyncAdaptersCache\$MySerializer
android.content.SyncAdaptersCache
android.content.SyncInfo\$1
android.content.SyncInfo
android.content.SyncRequest\$1
android.content.SyncRequest
android.content.SyncResult\$1
android.content.SyncResult
android.content.SyncStats\$1
android.content.SyncStats
android.content.SyncStatusInfo\$1
android.content.SyncStatusInfo
android.content.UndoOperation
android.content.UriPermission\$1
android.content.UriPermission
android.content.integrity.AtomicFormula\$BooleanAtomicFormula\$1
android.content.integrity.AtomicFormula\$LongAtomicFormula\$1
android.content.integrity.AtomicFormula\$StringAtomicFormula\$1
android.content.integrity.AtomicFormula
android.content.integrity.CompoundFormula\$1
android.content.integrity.CompoundFormula
android.content.integrity.IAppIntegrityManager
android.content.integrity.InstallerAllowedByManifestFormula\$1
android.content.integrity.InstallerAllowedByManifestFormula
android.content.integrity.Rule\$1
android.content.integrity.Rule
android.content.om.IOverlayManager
android.content.om.OverlayIdentifier\$1
android.content.om.OverlayIdentifier
android.content.om.OverlayInfo\$1
android.content.om.OverlayInfo
android.content.om.OverlayManagerTransaction\$1
android.content.om.OverlayManagerTransaction
android.content.pm.ActivityInfo\$1
android.content.pm.ApexStagedEvent\$1
android.content.pm.ApexStagedEvent
android.content.pm.ApkChecksum\$1
android.content.pm.ApkChecksum
android.content.pm.ApplicationInfo\$1\$\$ExternalSyntheticLambda0
android.content.pm.ApplicationInfo\$1
android.content.pm.ApplicationInfo
android.content.pm.Attribution\$1
android.content.pm.Attribution
android.content.pm.BaseParceledListSlice
android.content.pm.Capability\$1
android.content.pm.Capability
android.content.pm.CapabilityParams\$1
android.content.pm.CapabilityParams
android.content.pm.ChangedPackages\$1
android.content.pm.ChangedPackages
android.content.pm.Checksum\$1
android.content.pm.Checksum
android.content.pm.ComponentInfo
android.content.pm.ConfigurationInfo\$1
android.content.pm.ConfigurationInfo
android.content.pm.ConstrainDisplayApisConfig\$\$ExternalSyntheticLambda0
android.content.pm.DataLoaderParamsParcel\$1
android.content.pm.DataLoaderParamsParcel
android.content.pm.FeatureGroupInfo\$1
android.content.pm.FeatureGroupInfo
android.content.pm.FeatureInfo\$1
android.content.pm.FeatureInfo
android.content.pm.FileSystemControlParcel\$1
android.content.pm.FileSystemControlParcel
android.content.pm.ICrossProfileApps
android.content.pm.IDataLoader
android.content.pm.IDataLoaderManager
android.content.pm.IDataLoaderStatusListener
android.content.pm.IDexModuleRegisterCallback
android.content.pm.ILauncherApps
android.content.pm.IOnAppsChangedListener
android.content.pm.IOnChecksumsReadyListener
android.content.pm.IOtaDexopt
android.content.pm.IPackageChangeObserver
android.content.pm.IPackageDataObserver
android.content.pm.IPackageDeleteObserver2
android.content.pm.IPackageDeleteObserver
android.content.pm.IPackageInstallObserver2
android.content.pm.IPackageInstaller
android.content.pm.IPackageInstallerCallback
android.content.pm.IPackageInstallerSession
android.content.pm.IPackageInstallerSessionFileSystemConnector
android.content.pm.IPackageLoadingProgressCallback
android.content.pm.IPackageManager
android.content.pm.IPackageManagerNative
android.content.pm.IPackageMoveObserver
android.content.pm.IPackageStatsObserver
android.content.pm.IPinItemRequest
android.content.pm.IShortcutChangeCallback
android.content.pm.IShortcutService
android.content.pm.IStagedApexObserver
android.content.pm.IncrementalStatesInfo\$1
android.content.pm.IncrementalStatesInfo
android.content.pm.InstallSourceInfo\$1
android.content.pm.InstallSourceInfo
android.content.pm.InstallationFileParcel\$1
android.content.pm.InstallationFileParcel
android.content.pm.InstantAppInfo\$1
android.content.pm.InstantAppInfo
android.content.pm.InstantAppIntentFilter\$1
android.content.pm.InstantAppIntentFilter
android.content.pm.InstantAppRequestInfo\$1
android.content.pm.InstantAppRequestInfo
android.content.pm.InstantAppResolveInfo\$1
android.content.pm.InstantAppResolveInfo\$InstantAppDigest\$1
android.content.pm.InstantAppResolveInfo\$InstantAppDigest
android.content.pm.InstantAppResolveInfo
android.content.pm.InstrumentationInfo\$1
android.content.pm.InstrumentationInfo
android.content.pm.IntentFilterVerificationInfo\$1
android.content.pm.IntentFilterVerificationInfo
android.content.pm.KeySet\$1
android.content.pm.KeySet
android.content.pm.LabeledIntent\$1
android.content.pm.LauncherActivityInfoInternal\$1
android.content.pm.LauncherActivityInfoInternal
android.content.pm.LauncherApps\$AppUsageLimit\$1
android.content.pm.LauncherApps\$AppUsageLimit
android.content.pm.LauncherApps\$CallbackMessageHandler
android.content.pm.LauncherApps\$PinItemRequest\$1
android.content.pm.LauncherApps\$PinItemRequest
android.content.pm.LauncherApps\$ShortcutChangeCallbackProxy\$\$ExternalSyntheticLambda0
android.content.pm.LauncherApps\$ShortcutChangeCallbackProxy\$\$ExternalSyntheticLambda1
android.content.pm.ModuleInfo\$1
android.content.pm.ModuleInfo
android.content.pm.PackageChangeEvent\$1
android.content.pm.PackageChangeEvent
android.content.pm.PackageInfo\$1
android.content.pm.PackageInfo
android.content.pm.PackageInfoLite\$1
android.content.pm.PackageInfoLite
android.content.pm.PackageInstaller\$SessionCallbackDelegate\$\$ExternalSyntheticLambda0
android.content.pm.PackageInstaller\$SessionCallbackDelegate\$\$ExternalSyntheticLambda1
android.content.pm.PackageInstaller\$SessionCallbackDelegate\$\$ExternalSyntheticLambda3
android.content.pm.PackageInstaller\$SessionInfo\$1
android.content.pm.PackageInstaller\$SessionInfo
android.content.pm.PackageInstaller\$SessionParams\$1
android.content.pm.PackageInstaller\$SessionParams
android.content.pm.PackageManager\$1
android.content.pm.PackageManager\$2
android.content.pm.PackageManager\$ApplicationInfoFlags
android.content.pm.PackageManager\$ComponentEnabledSetting\$1
android.content.pm.PackageManager\$ComponentEnabledSetting
android.content.pm.PackageManager\$ComponentInfoFlags
android.content.pm.PackageManager\$LegacyPackageDeleteObserver
android.content.pm.PackageManager\$NameNotFoundException
android.content.pm.PackageManager\$PackageInfoFlags
android.content.pm.PackageManager\$Property\$1
android.content.pm.PackageManager\$Property
android.content.pm.PackageManager\$ResolveInfoFlags
android.content.pm.PackageParser\$Activity\$1
android.content.pm.PackageParser\$Activity
android.content.pm.PackageParser\$CallbackImpl
android.content.pm.PackageParser\$DefaultSplitAssetLoader
android.content.pm.PackageParser\$Instrumentation\$1
android.content.pm.PackageParser\$Instrumentation
android.content.pm.PackageParser\$Package\$1
android.content.pm.PackageParser\$Package
android.content.pm.PackageParser\$ParseComponentArgs
android.content.pm.PackageParser\$Permission\$1
android.content.pm.PackageParser\$Permission
android.content.pm.PackageParser\$PermissionGroup\$1
android.content.pm.PackageParser\$PermissionGroup
android.content.pm.PackageParser\$Provider\$1
android.content.pm.PackageParser\$Provider
android.content.pm.PackageParser\$Service\$1
android.content.pm.PackageParser\$Service
android.content.pm.PackageParser\$SigningDetails\$1
android.content.pm.PackageParser\$SigningDetails
android.content.pm.PackageParser\$SplitAssetDependencyLoader
android.content.pm.PackageParserCacheHelper\$ReadHelper
android.content.pm.PackageParserCacheHelper\$WriteHelper
android.content.pm.PackageStats\$1
android.content.pm.PackageStats
android.content.pm.PathPermission\$1
android.content.pm.PermissionGroupInfo\$1
android.content.pm.PermissionGroupInfo
android.content.pm.PermissionInfo\$1
android.content.pm.PermissionInfo
android.content.pm.ProcessInfo\$1
android.content.pm.ProcessInfo
android.content.pm.ProviderInfo\$1
android.content.pm.ProviderInfoList\$1
android.content.pm.ProviderInfoList
android.content.pm.RegisteredServicesCache\$1
android.content.pm.RegisteredServicesCache\$2
android.content.pm.RegisteredServicesCache\$3
android.content.pm.ResolveInfo\$1
android.content.pm.ResolveInfo
android.content.pm.ServiceInfo\$1
android.content.pm.SharedLibraryInfo\$1
android.content.pm.SharedLibraryInfo
android.content.pm.ShortcutInfo\$1
android.content.pm.ShortcutInfo
android.content.pm.ShortcutManager\$ShareShortcutInfo\$1
android.content.pm.ShortcutManager\$ShareShortcutInfo
android.content.pm.ShortcutQueryWrapper\$1
android.content.pm.ShortcutQueryWrapper
android.content.pm.Signature\$1
android.content.pm.Signature
android.content.pm.SigningDetails\$1
android.content.pm.SigningDetails
android.content.pm.SigningInfo\$1
android.content.pm.SigningInfo
android.content.pm.StagedApexInfo\$1
android.content.pm.StagedApexInfo
android.content.pm.SuspendDialogInfo\$1
android.content.pm.SuspendDialogInfo
android.content.pm.UserInfo\$1
android.content.pm.UserInfo
android.content.pm.VerifierDeviceIdentity\$1
android.content.pm.VerifierDeviceIdentity
android.content.pm.VerifierInfo\$1
android.content.pm.VerifierInfo
android.content.pm.VersionedPackage\$1
android.content.pm.VersionedPackage
android.content.pm.dex.IArtManager
android.content.pm.dex.ISnapshotRuntimeProfileCallback
android.content.pm.parsing.result.ParseTypeImpl\$\$ExternalSyntheticLambda0
android.content.pm.parsing.result.ParseTypeImpl\$\$ExternalSyntheticLambda1
android.content.pm.parsing.result.ParseTypeImpl
android.content.pm.permission.IRuntimePermissionPresenter
android.content.pm.permission.RuntimePermissionPresentationInfo\$1
android.content.pm.permission.RuntimePermissionPresentationInfo
android.content.pm.permission.SplitPermissionInfoParcelable\$1
android.content.pm.permission.SplitPermissionInfoParcelable
android.content.pm.pkg.FrameworkPackageUserStateDefault
android.content.pm.verify.domain.DomainOwner\$1
android.content.pm.verify.domain.DomainOwner
android.content.pm.verify.domain.DomainSet\$1
android.content.pm.verify.domain.DomainSet
android.content.pm.verify.domain.DomainVerificationInfo\$1
android.content.pm.verify.domain.DomainVerificationInfo
android.content.pm.verify.domain.DomainVerificationRequest\$1
android.content.pm.verify.domain.DomainVerificationRequest
android.content.pm.verify.domain.DomainVerificationUserState\$1
android.content.pm.verify.domain.DomainVerificationUserState
android.content.pm.verify.domain.IDomainVerificationManager
android.content.res.AssetFileDescriptor\$1
android.content.res.AssetFileDescriptor\$AutoCloseInputStream
android.content.res.AssetFileDescriptor\$AutoCloseOutputStream
android.content.res.AssetFileDescriptor
android.content.res.ColorStateList\$1
android.content.res.ColorStateList\$ColorStateListFactory
android.content.res.ColorStateList
android.content.res.CompatResources
android.content.res.CompatibilityInfo\$2
android.content.res.CompatibilityInfo
android.content.res.Configuration\$1
android.content.res.Configuration
android.content.res.ConfigurationBoundResourceCache
android.content.res.DrawableCache
android.content.res.FontResourcesParser\$FontFamilyFilesResourceEntry
android.content.res.FontResourcesParser\$ProviderResourceEntry
android.content.res.GradientColor\$GradientColorFactory
android.content.res.GradientColor
android.content.res.IResourcesManager
android.content.res.ObbInfo\$1
android.content.res.ObbInfo
android.content.res.Resources\$UpdateCallbacks
android.content.res.ResourcesImpl\$\$ExternalSyntheticLambda0
android.content.res.XmlResourceParser
android.content.rollback.IRollbackManager
android.content.rollback.PackageRollbackInfo\$1
android.content.rollback.PackageRollbackInfo
android.content.rollback.RollbackInfo\$1
android.content.rollback.RollbackInfo
android.content.rollback.RollbackManagerFrameworkInitializer\$\$ExternalSyntheticLambda0
android.content.ContentProvider
android.content.ContentProviderNative
android.content.ContentProviderProxy
android.content.ContentResolver\$1
android.content.ContentResolver\$ParcelFileDescriptorInner
android.content.ContentResolver\$StringResultListener
android.content.ContentResolver\$UriResultListener
android.content.CursorLoader
android.content.IClipboard\$Default
android.content.IClipboard\$Stub\$Proxy
android.content.IClipboard\$Stub
android.content.IContentService\$Default
android.content.IContentService\$Stub\$Proxy
android.content.IContentService\$Stub
android.content.IIntentReceiver\$Default
android.content.IIntentReceiver\$Stub\$Proxy
android.content.IIntentReceiver\$Stub
android.content.IIntentSender\$Default
android.content.IIntentSender\$Stub\$Proxy
android.content.IIntentSender\$Stub
android.content.IOnPrimaryClipChangedListener\$Default
android.content.IOnPrimaryClipChangedListener\$Stub\$Proxy
android.content.IOnPrimaryClipChangedListener\$Stub
android.content.IRestrictionsManager\$Default
android.content.IRestrictionsManager\$Stub\$Proxy
android.content.IRestrictionsManager\$Stub
android.content.ISyncAdapter\$Default
android.content.ISyncAdapter\$Stub\$Proxy
android.content.ISyncAdapter\$Stub
android.content.ISyncAdapterUnsyncableAccountCallback\$Default
android.content.ISyncAdapterUnsyncableAccountCallback\$Stub\$Proxy
android.content.ISyncAdapterUnsyncableAccountCallback\$Stub
android.content.ISyncContext\$Default
android.content.ISyncContext\$Stub\$Proxy
android.content.ISyncContext\$Stub
android.content.ISyncServiceAdapter\$Default
android.content.ISyncServiceAdapter\$Stub\$Proxy
android.content.ISyncServiceAdapter\$Stub
android.content.ISyncStatusObserver\$Default
android.content.ISyncStatusObserver\$Stub\$Proxy
android.content.ISyncStatusObserver\$Stub
android.content.MutableContextWrapper
android.content.integrity.AtomicFormula\$BooleanAtomicFormula
android.content.integrity.AtomicFormula\$LongAtomicFormula
android.content.integrity.AtomicFormula\$StringAtomicFormula
android.content.integrity.IAppIntegrityManager\$Default
android.content.integrity.IAppIntegrityManager\$Stub\$Proxy
android.content.integrity.IAppIntegrityManager\$Stub
android.content.om.IOverlayManager\$Default
android.content.om.IOverlayManager\$Stub\$Proxy
android.content.om.IOverlayManager\$Stub
android.content.pm.ActivityInfo
android.content.pm.AuxiliaryResolveInfo\$AuxiliaryFilter
android.content.pm.BaseParceledListSlice\$1
android.content.pm.ICrossProfileApps\$Default
android.content.pm.ICrossProfileApps\$Stub\$Proxy
android.content.pm.ICrossProfileApps\$Stub
android.content.pm.IDataLoader\$Default
android.content.pm.IDataLoader\$Stub\$Proxy
android.content.pm.IDataLoader\$Stub
android.content.pm.IDataLoaderManager\$Default
android.content.pm.IDataLoaderManager\$Stub\$Proxy
android.content.pm.IDataLoaderManager\$Stub
android.content.pm.IDataLoaderStatusListener\$Default
android.content.pm.IDataLoaderStatusListener\$Stub\$Proxy
android.content.pm.IDataLoaderStatusListener\$Stub
android.content.pm.IDexModuleRegisterCallback\$Default
android.content.pm.IDexModuleRegisterCallback\$Stub\$Proxy
android.content.pm.IDexModuleRegisterCallback\$Stub
android.content.pm.ILauncherApps\$Default
android.content.pm.ILauncherApps\$Stub\$Proxy
android.content.pm.ILauncherApps\$Stub
android.content.pm.IOnAppsChangedListener\$Default
android.content.pm.IOnAppsChangedListener\$Stub\$Proxy
android.content.pm.IOnAppsChangedListener\$Stub
android.content.pm.IOnChecksumsReadyListener\$Default
android.content.pm.IOnChecksumsReadyListener\$Stub\$Proxy
android.content.pm.IOnChecksumsReadyListener\$Stub
android.content.pm.IOtaDexopt\$Default
android.content.pm.IOtaDexopt\$Stub\$Proxy
android.content.pm.IOtaDexopt\$Stub
android.content.pm.IPackageChangeObserver\$Default
android.content.pm.IPackageChangeObserver\$Stub\$Proxy
android.content.pm.IPackageChangeObserver\$Stub
android.content.pm.IPackageDataObserver\$Default
android.content.pm.IPackageDataObserver\$Stub\$Proxy
android.content.pm.IPackageDataObserver\$Stub
android.content.pm.IPackageDeleteObserver\$Default
android.content.pm.IPackageDeleteObserver\$Stub\$Proxy
android.content.pm.IPackageDeleteObserver\$Stub
android.content.pm.IPackageDeleteObserver2\$Default
android.content.pm.IPackageDeleteObserver2\$Stub\$Proxy
android.content.pm.IPackageDeleteObserver2\$Stub
android.content.pm.IPackageInstallObserver2\$Default
android.content.pm.IPackageInstallObserver2\$Stub\$Proxy
android.content.pm.IPackageInstallObserver2\$Stub
android.content.pm.IPackageInstaller\$Default
android.content.pm.IPackageInstaller\$Stub\$Proxy
android.content.pm.IPackageInstaller\$Stub
android.content.pm.IPackageInstallerCallback\$Default
android.content.pm.IPackageInstallerCallback\$Stub\$Proxy
android.content.pm.IPackageInstallerCallback\$Stub
android.content.pm.IPackageInstallerSession\$Default
android.content.pm.IPackageInstallerSession\$Stub\$Proxy
android.content.pm.IPackageInstallerSession\$Stub
android.content.pm.IPackageInstallerSessionFileSystemConnector\$Default
android.content.pm.IPackageInstallerSessionFileSystemConnector\$Stub\$Proxy
android.content.pm.IPackageInstallerSessionFileSystemConnector\$Stub
android.content.pm.IPackageLoadingProgressCallback\$Default
android.content.pm.IPackageLoadingProgressCallback\$Stub\$Proxy
android.content.pm.IPackageLoadingProgressCallback\$Stub
android.content.pm.IPackageManager\$Default
android.content.pm.IPackageManager\$Stub\$Proxy
android.content.pm.IPackageManager\$Stub
android.content.pm.IPackageManagerNative\$Default
android.content.pm.IPackageManagerNative\$Stub\$Proxy
android.content.pm.IPackageManagerNative\$Stub
android.content.pm.IPackageMoveObserver\$Default
android.content.pm.IPackageMoveObserver\$Stub\$Proxy
android.content.pm.IPackageMoveObserver\$Stub
android.content.pm.IPackageStatsObserver\$Default
android.content.pm.IPackageStatsObserver\$Stub\$Proxy
android.content.pm.IPackageStatsObserver\$Stub
android.content.pm.IPinItemRequest\$Default
android.content.pm.IPinItemRequest\$Stub\$Proxy
android.content.pm.IPinItemRequest\$Stub
android.content.pm.IShortcutChangeCallback\$Default
android.content.pm.IShortcutChangeCallback\$Stub\$Proxy
android.content.pm.IShortcutChangeCallback\$Stub
android.content.pm.IShortcutService\$Default
android.content.pm.IShortcutService\$Stub\$Proxy
android.content.pm.IShortcutService\$Stub
android.content.pm.IStagedApexObserver\$Default
android.content.pm.IStagedApexObserver\$Stub\$Proxy
android.content.pm.IStagedApexObserver\$Stub
android.content.pm.LabeledIntent
android.content.pm.PackageParser\$IntentInfo
android.content.pm.ParceledListSlice\$1
android.content.pm.ParceledListSlice
android.content.pm.PathPermission
android.content.pm.ProviderInfo
android.content.pm.ServiceInfo
android.content.pm.StringParceledListSlice\$1
android.content.pm.StringParceledListSlice
android.content.pm.dex.IArtManager\$Default
android.content.pm.dex.IArtManager\$Stub\$Proxy
android.content.pm.dex.IArtManager\$Stub
android.content.pm.dex.ISnapshotRuntimeProfileCallback\$Default
android.content.pm.dex.ISnapshotRuntimeProfileCallback\$Stub\$Proxy
android.content.pm.dex.ISnapshotRuntimeProfileCallback\$Stub
android.content.pm.permission.IRuntimePermissionPresenter\$Default
android.content.pm.permission.IRuntimePermissionPresenter\$Stub\$Proxy
android.content.pm.permission.IRuntimePermissionPresenter\$Stub
android.content.pm.verify.domain.IDomainVerificationManager\$Default
android.content.pm.verify.domain.IDomainVerificationManager\$Stub\$Proxy
android.content.pm.verify.domain.IDomainVerificationManager\$Stub
android.content.res.CompatibilityInfo\$1
android.content.res.IResourcesManager\$Default
android.content.res.IResourcesManager\$Stub\$Proxy
android.content.res.IResourcesManager\$Stub
android.content.res.Resources\$AssetManagerUpdateHandler
android.content.res.XmlBlock\$Parser
android.content.rollback.IRollbackManager\$Default
android.content.rollback.IRollbackManager\$Stub\$Proxy
android.content.rollback.IRollbackManager\$Stub
android.content.AbstractThreadedSyncAdapter\$ISyncAdapterImpl
android.content.ClipboardManager\$1
android.content.ContentProvider\$Transport
android.content.ContentProviderClient\$CursorWrapperInner
android.content.ContentResolver\$2
android.content.ContentResolver\$CursorWrapperInner
android.content.IntentSender\$FinishedDispatcher
android.content.SearchRecentSuggestionsProvider
android.content.pm.LauncherApps\$1
android.content.pm.LauncherApps\$ShortcutChangeCallbackProxy
android.content.pm.PackageInstaller\$Session\$1
android.content.pm.PackageInstaller\$SessionCallbackDelegate
android.content.pm.PackageParser\$ActivityIntentInfo
android.content.pm.PackageParser\$ProviderIntentInfo
android.content.pm.PackageParser\$ServiceIntentInfo
android.content.pm.dex.ArtManager\$SnapshotRuntimeProfileCallbackDelegate
android.content.SyncActivityTooManyDeletes
android.content.res.StringBlock\$Height " | parallel -j 12 python3 OffsetAnalysis.py {} content-class/{} _result.txt